# Project Notes - Machine Learning

The following notebook is a summary of the steps taken in the final project for Intro to Machine Learning.  

### Tools Used
For this project I used the following:

* Jupyter Notebook - for notekeeping and data exploration
* Github - project submission
* PyCharm - for Python script coding


### Data Exploration

Data was loaded into the notebook and read into a dataframe to gain initial stats summary and to spot potention data errors.

When inspecting the data there are 21 features as follows:

financial features in US dollars: ['salary', 'deferral_payments', 'total_payments', 'loan_advances', 'bonus', 'restricted_stock_deferred', 'deferred_income', 'total_stock_value', 'expenses', 'exercised_stock_options', 'other', 'long_term_incentive', 'restricted_stock', 'director_fees'] 

email features: ['to_messages', 'email_address', 'from_poi_to_this_person', 'from_messages', 'from_this_person_to_poi', 'shared_receipt_with_poi'] (units are generally number of emails messages; notable exception is ‘email_address’, which is a text string)

POI label: [‘poi’] (boolean, represented as integer)


### [Project Questions and Summary](https://github.com/troberts777/C753-Identify-Fraud-from-Enron-Email/blob/main/Project%20Questions.pdf)

In [1]:
# import some libraries
import pickle as pkl
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib.lines as mlines

In [2]:
# Load the dictionary containing the dataset
with open("final_project_dataset.pkl", "r") as data_file:
    data_dict = pkl.load(data_file)

# make a pandas dataframe to explore
enron_df = pd.DataFrame.from_dict(data_dict,orient='index')

In [3]:
# check the data structure
enron_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 146 entries, ALLEN PHILLIP K to YEAP SOON
Data columns (total 21 columns):
salary                       146 non-null object
to_messages                  146 non-null object
deferral_payments            146 non-null object
total_payments               146 non-null object
exercised_stock_options      146 non-null object
bonus                        146 non-null object
restricted_stock             146 non-null object
shared_receipt_with_poi      146 non-null object
restricted_stock_deferred    146 non-null object
total_stock_value            146 non-null object
expenses                     146 non-null object
loan_advances                146 non-null object
from_messages                146 non-null object
other                        146 non-null object
from_this_person_to_poi      146 non-null object
poi                          146 non-null bool
director_fees                146 non-null object
deferred_income              146 non-null object
long_term_incentive          146 non-null object
email_address                146 non-null object
from_poi_to_this_person      146 non-null object
dtypes: bool(1), object(20)
memory usage: 24.1+ KB

**Dataset 21 columns 146 rows**

In [4]:
# Checking the dataset
enron_df.head()

,salary,to_messages,deferral_payments,total_payments,exercised_stock_options,bonus,restricted_stock,shared_receipt_with_poi,restricted_stock_deferred,total_stock_value,...,loan_advances,from_messages,other,from_this_person_to_poi,poi,director_fees,deferred_income,long_term_incentive,email_address,from_poi_to_this_person
ALLEN PHILLIP K,201955,2902,2869717,4484442,1729541,4175000,126027,1407,-126027,1729541,...,NaN,2195,152,65,False,NaN,-3081055,304805,phillip.allen@enron.com,47
BADUM JAMES P,NaN,NaN,178980,182466,257817,NaN,NaN,NaN,NaN,257817,...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN
BANNANTINE JAMES M,477,566,NaN,916197,4046157,NaN,1757552,465,-560222,5243487,...,NaN,29,864523,0,False,NaN,-5104,NaN,james.bannantine@enron.com,39
BAXTER JOHN C,267102,NaN,1295738,5634343,6680544,1200000,3942714,NaN,NaN,10623258,...,NaN,NaN,2660303,NaN,False,NaN,-1386055,1586055,NaN,NaN
BAY FRANKLIN R,239671,NaN,260455,827696,NaN,400000,145796,NaN,-82782,63014,...,NaN,NaN,69,NaN,False,NaN,-201641,NaN,frank.bay@enron.com,NaN

Let's reorganize the data

In [5]:
# Formatting for the output:
pd.set_option('display.float_format', lambda x: '%.3f' % x)

# Convert dictionary to DataFrame
enron_df = pd.DataFrame.from_dict(data_dict, orient = 'index', dtype = float)

# reorganize columns
enron_df = enron_df[
['salary',
'bonus',
'long_term_incentive',
'deferred_income',
'deferral_payments',
'loan_advances',
'other',
'expenses',
'director_fees',
'total_payments',
 'exercised_stock_options',
'restricted_stock',
 'restricted_stock_deferred',
 'total_stock_value',
 'email_address',
 'to_messages',
 'shared_receipt_with_poi',
 'from_messages',
 'from_this_person_to_poi',
 'poi',
 'from_poi_to_this_person']]

In [6]:
# Check the dataset
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

enron_df

,salary,bonus,long_term_incentive,deferred_income,deferral_payments,loan_advances,other,expenses,director_fees,total_payments,exercised_stock_options,restricted_stock,restricted_stock_deferred,total_stock_value,email_address,to_messages,shared_receipt_with_poi,from_messages,from_this_person_to_poi,poi,from_poi_to_this_person
ALLEN PHILLIP K,201955.000,4175000.000,304805.000,-3081055.000,2869717.000,nan,152.000,13868.000,nan,4484442.000,1729541.000,126027.000,-126027.000,1729541.000,phillip.allen@enron.com,2902.000,1407.000,2195.000,65.000,0.000,47.000
BADUM JAMES P,nan,nan,nan,nan,178980.000,nan,nan,3486.000,nan,182466.000,257817.000,nan,nan,257817.000,NaN,nan,nan,nan,nan,0.000,nan
BANNANTINE JAMES M,477.000,nan,nan,-5104.000,nan,nan,864523.000,56301.000,nan,916197.000,4046157.000,1757552.000,-560222.000,5243487.000,james.bannantine@enron.com,566.000,465.000,29.000,0.000,0.000,39.000
BAXTER JOHN C,267102.000,1200000.000,1586055.000,-1386055.000,1295738.000,nan,2660303.000,11200.000,nan,5634343.000,6680544.000,3942714.000,nan,10623258.000,NaN,nan,nan,nan,nan,0.000,nan
BAY FRANKLIN R,239671.000,400000.000,nan,-201641.000,260455.000,nan,69.000,129142.000,nan,827696.000,nan,145796.000,-82782.000,63014.000,frank.bay@enron.com,nan,nan,nan,nan,0.000,nan
BAZELIDES PHILIP J,80818.000,nan,93750.000,nan,684694.000,nan,874.000,nan,nan,860136.000,1599641.000,nan,nan,1599641.000,NaN,nan,nan,nan,nan,0.000,nan
BECK SALLY W,231330.000,700000.000,nan,nan,nan,nan,566.000,37172.000,nan,969068.000,nan,126027.000,nan,126027.000,sally.beck@enron.com,7315.000,2639.000,4343.000,386.000,0.000,144.000
BELDEN TIMOTHY N,213999.000,5249999.000,nan,-2334434.000,2144013.000,nan,210698.000,17355.000,nan,5501630.000,953136.000,157569.000,nan,1110705.000,tim.belden@enron.com,7991.000,5521.000,484.000,108.000,1.000,228.000
BELFER ROBERT,nan,nan,nan,nan,-102500.000,nan,nan,nan,3285.000,102500.000,3285.000,nan,44093.000,-44093.000,NaN,nan,nan,nan,nan,0.000,nan
BERBERIAN DAVID,216582.000,nan,nan,nan,nan,nan,nan,11892.000,nan,228474.000,1624396.000,869220.000,nan,2493616.000,david.berberian@enron.com,nan,nan,nan,nan,0.000,nan
BERGSIEKER RICHARD P,187922.000,250000.000,180250.000,-485813.000,nan,nan,427316.000,59175.000,nan,618850.000,nan,659249.000,nan,659249.000,rick.bergsieker@enron.com,383.000,233.000,59.000,0.000,0.000,4.000
BHATNAGAR SANJAY,nan,nan,nan,nan,nan,nan,137864.000,nan,137864.000,15456290.000,2604490.000,-2604490.000,15456290.000,nan,sanjay.bhatnagar@enron.com,523.000,463.000,29.000,1.000,0.000,0.000
BIBI PHILIPPE A,213625.000,1000000.000,369721.000,nan,nan,nan,425688.000,38559.000,nan,2047593.000,1465734.000,378082.000,nan,1843816.000,philippe.bibi@enron.com,1607.000,1336.000,40.000,8.000,0.000,23.000
BLACHMAN JEREMY M,248546.000,850000.000,831809.000,nan,nan,nan,272.000,84208.000,nan,2014835.000,765313.000,189041.000,nan,954354.000,jeremy.blachman@enron.com,2475.000,2326.000,14.000,2.000,0.000,25.000
BLAKE JR. NORMAN P,nan,nan,nan,-113784.000,nan,nan,nan,1279.000,113784.000,1279.000,nan,nan,nan,nan,NaN,nan,nan,nan,nan,0.000,nan
BOWEN JR RAYMOND M,278601.000,1350000.000,974293.000,-833.000,nan,nan,1621.000,65907.000,nan,2669589.000,nan,252055.000,nan,252055.000,raymond.bowen@enron.com,1858.000,1593.000,27.000,15.000,1.000,140.000
BROWN MICHAEL,nan,nan,nan,nan,nan,nan,nan,49288.000,nan,49288.000,nan,nan,nan,nan,michael.brown@enron.com,1486.000,761.000,41.000,1.000,0.000,13.000
BUCHANAN HAROLD G,248017.000,500000.000,304805.000,nan,nan,nan,1215.000,600.000,nan,1054637.000,825464.000,189041.000,nan,1014505.000,john.buchanan@enron.com,1088.000,23.000,125.000,0.000,0.000,0.000
BUTTS ROBERT H,261516.000,750000.000,175000.000,-75000.000,nan,nan,150656.000,9410.000,nan,1271582.000,nan,417619.000,nan,417619.000,bob.butts@enron.com,nan,nan,nan,nan,0.000,nan
BUY RICHARD B,330546.000,900000.000,769862.000,-694862.000,649584.000,nan,400572.000,nan,nan,2355702.000,2542813.000,901657.000,nan,3444470.000,rick.buy@enron.com,3523.000,2333.000,1053.000,71.000,0.000,156.000
CALGER CHRISTOPHER F,240189.000,1250000.000,375304.000,-262500.000,nan,nan,486.000,35818.000,nan,1639297.000,nan,126027.000,nan,126027.000,christopher.calger@enron.com,2598.000,2188.000,144.000,25.000,1.000,199.000
CARTER REBECCA C,261809.000,300000.000,75000.000,-159792.000,nan,nan,540.000,nan,nan,477557.000,nan,307301.000,-307301.000,nan,rebecca.carter@enron.com,312.000,196.000,15.000,7.000,0.000,29.000
CAUSEY RICHARD A,415189.000,1000000.000,350000.000,-235000.000,nan,nan,307895.000,30674.000,nan,1868758.000,nan,2502063.000,nan,2502063.000,richard.causey@enron.com,1892.000,1585.000,49.000,12.000,1.000,58.000
CHAN RONNIE,nan,nan,nan,-98784.000,nan,nan,nan,nan,98784.000,nan,nan,32460.000,-32460.000,nan,NaN,nan,nan,nan,nan,0.000,nan
CHRISTODOULOU DIOMEDES,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,5127155.000,950730.000,nan,6077885.000,diomedes.christodoulou@enron.com,nan,nan,nan,nan,0.000,nan
CLINE KENNETH W,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,662086.000,-472568.000,189518.000,NaN,nan,nan,nan,nan,0.000,nan
COLWELL WESLEY,288542.000,1200000.000,nan,-144062.000,27610.000,nan,101740.000,16514.000,nan,1490344.000,nan,698242.000,nan,698242.000,wes.colwell@enron.com,1758.000,1132.000,40.000,11.000,1.000,240.000
CORDES WILLIAM R,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,651850.000,386335.000,nan,1038185.000,bill.cordes@enron.com,764.000,58.000,12.000,0.000,0.000,10.000
COX DAVID,314288.000,800000.000,nan,-41250.000,nan,nan,494.000,27861.000,nan,1101393.000,117551.000,378082.000,nan,495633.000,chip.cox@enron.com,102.000,71.000,33.000,4.000,0.000,0.000
CUMBERLAND MICHAEL S,184899.000,325000.000,275000.000,nan,nan,nan,713.000,22344.000,nan,807956.000,nan,207940.000,nan,207940.000,NaN,nan,nan,nan,nan,0.000,nan
DEFFNER JOSEPH M,206121.000,600000.000,335349.000,nan,nan,nan,25553.000,41626.000,nan,1208649.000,17378.000,141833.000,nan,159211.000,joseph.deffner@enron.com,714.000,552.000,74.000,4.000,0.000,115.000
DELAINEY DAVID W,365163.000,3000000.000,1294981.000,nan,nan,nan,1661.000,86174.000,nan,4747979.000,2291113.000,1323148.000,nan,3614261.000,david.delainey@enron.com,3093.000,2097.000,3069.000,609.000,1.000,66.000
DERRICK JR. JAMES V,492375.000,800000.000,484000.000,-1284000.000,nan,nan,7482.000,51124.000,nan,550981.000,8831913.000,1787380.000,-1787380.000,8831913.000,james.derrick@enron.com,2181.000,1401.000,909.000,20.000,0.000,64.000
DETMERING TIMOTHY J,210500.000,425000.000,415657.000,-775241.000,875307.000,nan,1105.000,52255.000,nan,1204583.000,2027865.000,315068.000,-315068.000,2027865.000,timothy.detmering@enron.com,nan,nan,nan,nan,0.000,nan
DIETRICH JANET R,250100.000,600000.000,556416.000,nan,nan,nan,473.000,3475.000,nan,1410464.000,1550019.000,315068.000,nan,1865087.000,janet.dietrich@enron.com,2572.000,1902.000,63.000,14.000,0.000,305.000
DIMICHELE RICHARD G,262788.000,1000000.000,694862.000,nan,nan,nan,374689.000,35812.000,nan,2368151.000,8191755.000,126027.000,nan,8317782.000,richard.dimichele@enron.com,nan,nan,nan,nan,0.000,nan
DODSON KEITH,221003.000,70000.000,nan,nan,nan,nan,774.000,28164.000,nan,319941.000,nan,nan,nan,nan,keith.dodson@enron.com,176.000,114.000,14.000,3.000,0.000,10.000
DONAHUE JR JEFFREY M,278601.000,800000.000,nan,-300000.000,nan,nan,891.000,96268.000,nan,875760.000,765920.000,315068.000,nan,1080988.000,jeff.donahue@enron.com,865.000,772.000,22.000,11.000,0.000,188.000
DUNCAN JOHN H,nan,nan,nan,-25000.000,nan,nan,nan,nan,102492.000,77492.000,371750.000,nan,nan,371750.000,NaN,nan,nan,nan,nan,0.000,nan
DURAN WILLIAM D,210692.000,750000.000,1105218.000,nan,nan,nan,1568.000,25785.000,nan,2093263.000,1451869.000,189041.000,nan,1640910.000,w.duran@enron.com,904.000,599.000,12.000,3.000,0.000,106.000
ECHOLS JOHN B,182245.000,200000.000,2234774.000,nan,nan,nan,53775.000,21530.000,nan,2692324.000,601438.000,407503.000,nan,1008941.000,john.echols@enron.com,nan,nan,nan,nan,0.000,nan
ELLIOTT STEVEN,170941.000,350000.000,nan,-400729.000,nan,nan,12961.000,78552.000,nan,211725.000,4890344.000,1788391.000,nan,6678735.000,steven.elliott@enron.com,nan,nan,nan,nan,0.000,nan
FALLON JAMES B,304588.000,2500000.000,374347.000,nan,nan,nan,401481.000,95924.000,nan,3676340.000,940257.000,1392142.000,nan,2332399.000,jim.fallon@enron.com,1755.000,1604.000,75.000,37.000,0.000,42.000
FASTOW ANDREW S,440698.000,1300000.000,1736055.000,-1386055.000,nan,nan,277464.000,55921.000,nan,2424083.000,nan,1794412.000,nan,1794412.000,andrew.fastow@enron.com,nan,nan,nan,nan,1.000,nan
FITZGERALD JAY L,199157.000,350000.000,556416.000,nan,nan,nan,285414.000,23870.000,nan,1414857.000,664461.000,956775.000,nan,1621236.000,jay.fitzgerald@enron.com,936.000,723.000,16.000,8.000,0.000,1.000
FOWLER PEGGY,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1324578.000,560170.000,nan,1884748.000,kulvinder.fowler@enron.com,517.000,10.000,36.000,0.000,0.000,0.000
FOY JOE,nan,nan,nan,nan,181755.000,nan,nan,nan,nan,181755.000,343434.000,nan,nan,343434.000,tracy.foy@enron.com,57.000,2.000,13.000,0.000,0.000,0.000
FREVERT MARK A,1060932.000,2000000.000,1617011.000,-3367011.000,6426990.000,2000000.000,7427621.000,86987.000,nan,17252530.000,10433518.000,4188667.000,nan,14622185.000,mark.frevert@enron.com,3275.000,2979.000,21.000,6.000,0.000,242.000
FUGH JOHN L,nan,nan,nan,nan,50591.000,nan,nan,nan,nan,50591.000,176378.000,nan,nan,176378.000,NaN,nan,nan,nan,nan,0.000,nan
GAHN ROBERT S,192008.000,509870.000,nan,-1042.000,73122.000,nan,76547.000,50080.000,nan,900585.000,83237.000,235370.000,nan,318607.000,NaN,nan,nan,nan,nan,0.000,nan
GARLAND C KEVIN,231946.000,850000.000,375304.000,nan,nan,nan,60814.000,48405.000,nan,1566469.000,636246.000,259907.000,nan,896153.000,kevin.garland@enron.com,209.000,178.000,44.000,27.000,0.000,10.000
GATHMANN WILLIAM D,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1753766.000,264013.000,-72419.000,1945360.000,NaN,nan,nan,nan,nan,0.000,nan
GIBBS DANA R,nan,nan,461912.000,nan,504610.000,nan,nan,nan,nan,966522.000,2218275.000,nan,nan,2218275.000,dana.gibbs@enron.com,169.000,23.000,12.000,0.000,0.000,0.000
GILLIS JOHN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,9803.000,75838.000,nan,85641.000,NaN,nan,nan,nan,nan,0.000,nan
GLISAN JR BEN F,274975.000,600000.000,71023.000,nan,nan,nan,200308.000,125978.000,nan,1272284.000,384728.000,393818.000,nan,778546.000,ben.glisan@enron.com,873.000,874.000,16.000,6.000,1.000,52.000
GOLD JOSEPH,272880.000,750000.000,304805.000,nan,nan,nan,819288.000,nan,nan,2146973.000,436515.000,441096.000,nan,877611.000,joe.gold@enron.com,nan,nan,nan,nan,0.000,nan
GRAMM WENDY L,nan,nan,nan,nan,nan,nan,nan,nan,119292.000,119292.000,nan,nan,nan,nan,NaN,nan,nan,nan,nan,0.000,nan
GRAY RODNEY,6615.000,nan,365625.000,nan,93585.000,nan,680833.000,nan,nan,1146658.000,nan,nan,nan,nan,NaN,nan,nan,nan,nan,0.000,nan
HAEDICKE MARK E,374125.000,1150000.000,983346.000,-934484.000,2157527.000,nan,52382.000,76169.000,nan,3859065.000,608750.000,524169.000,-329825.000,803094.000,mark.haedicke@enron.com,4009.000,1847.000,1941.000,61.000,0.000,180.000
HANNON KEVIN P,243293.000,1500000.000,1617011.000,-3117011.000,nan,nan,11350.000,34039.000,nan,288682.000,5538001.000,853064.000,nan,6391065.000,kevin.hannon@enron.com,1045.000,1035.000,32.000,21.000,1.000,32.000
HAUG DAVID L,nan,nan,nan,nan,nan,nan,nan,475.000,nan,475.000,nan,2217299.000,nan,2217299.000,david.haug@enron.com,573.000,471.000,19.000,7.000,0.000,4.000
HAYES ROBERT E,nan,nan,nan,nan,7961.000,nan,nan,nan,nan,7961.000,nan,151418.000,nan,151418.000,robert.hayes@enron.com,504.000,50.000,12.000,0.000,0.000,16.000
HAYSLETT RODERICK J,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,346663.000,nan,346663.000,rod.hayslett@enron.com,2649.000,571.000,1061.000,38.000,0.000,35.000
HERMANN ROBERT J,262663.000,700000.000,150000.000,-280000.000,nan,nan,416441.000,48357.000,nan,1297461.000,187500.000,480632.000,nan,668132.000,robert.hermann@enron.com,nan,nan,nan,nan,0.000,nan
HICKERSON GARY J,211788.000,1700000.000,69223.000,nan,nan,nan,1936.000,98849.000,nan,2081796.000,nan,441096.000,nan,441096.000,gary.hickerson@enron.com,1320.000,900.000,27.000,1.000,0.000,40.000
HIRKO JOSEPH,nan,nan,nan,nan,10259.000,nan,2856.000,77978.000,nan,91093.000,30766064.000,nan,nan,30766064.000,joe.hirko@enron.com,nan,nan,nan,nan,1.000,nan
HORTON STANLEY C,nan,nan,nan,nan,3131860.000,nan,nan,nan,nan,3131860.000,5210569.000,2046079.000,nan,7256648.000,stanley.horton@enron.com,2350.000,1074.000,1073.000,15.000,0.000,44.000
HUGHES JAMES A,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,754966.000,363428.000,nan,1118394.000,james.hughes@enron.com,719.000,589.000,34.000,5.000,0.000,35.000
HUMPHREY GENE E,130724.000,nan,nan,nan,2964506.000,nan,nan,4994.000,nan,3100224.000,2282768.000,nan,nan,2282768.000,gene.humphrey@enron.com,128.000,119.000,17.000,17.000,0.000,10.000
IZZO LAWRENCE L,85274.000,nan,312500.000,nan,nan,nan,1553729.000,28093.000,nan,1979596.000,2165172.000,3654808.000,nan,5819980.000,larry.izzo@enron.com,496.000,437.000,19.000,5.000,0.000,28.000
JACKSON CHARLENE R,288558.000,250000.000,nan,nan,nan,nan,2435.000,10181.000,nan,551174.000,185063.000,540672.000,nan,725735.000,charlene.jackson@enron.com,258.000,117.000,56.000,19.000,0.000,25.000
JAEDICKE ROBERT,nan,nan,nan,-25000.000,nan,nan,nan,nan,108750.000,83750.000,431750.000,44093.000,-44093.000,431750.000,NaN,nan,nan,nan,nan,0.000,nan
KAMINSKI WINCENTY J,275101.000,400000.000,323466.000,nan,nan,nan,4669.000,83585.000,nan,1086821.000,850010.000,126027.000,nan,976037.000,vince.kaminski@enron.com,4607.000,583.000,14368.000,171.000,0.000,41.000
KEAN STEVEN J,404338.000,1000000.000,300000.000,nan,nan,nan,1231.000,41953.000,nan,1747522.000,2022048.000,4131594.000,nan,6153642.000,steven.kean@enron.com,12754.000,3639.000,6759.000,387.000,0.000,140.000
KISHKILL JOSEPH G,174246.000,nan,nan,-51042.000,nan,nan,465357.000,116335.000,nan,704896.000,nan,1034346.000,nan,1034346.000,joe.kishkill@enron.com,nan,nan,nan,nan,0.000,nan
KITCHEN LOUISE,271442.000,3100000.000,nan,nan,nan,nan,93925.000,5774.000,nan,3471141.000,81042.000,466101.000,nan,547143.000,louise.kitchen@enron.com,8305.000,3669.000,1728.000,194.000,0.000,251.000
KOENIG MARK E,309946.000,700000.000,300000.000,nan,nan,nan,150458.000,127017.000,nan,1587421.000,671737.000,1248318.000,nan,1920055.000,mark.koenig@enron.com,2374.000,2271.000,61.000,15.000,1.000,53.000
KOPPER MICHAEL J,224305.000,800000.000,602671.000,nan,nan,nan,907502.000,118134.000,nan,2652612.000,nan,985032.000,nan,985032.000,michael.kopper@enron.com,nan,nan,nan,nan,1.000,nan
LAVORATO JOHN J,339288.000,8000000.000,2035380.000,nan,nan,nan,1552.000,49537.000,nan,10425757.000,4158995.000,1008149.000,nan,5167144.000,john.lavorato@enron.com,7259.000,3962.000,2585.000,411.000,0.000,528.000
LAY KENNETH L,1072321.000,7000000.000,3600000.000,-300000.000,202911.000,81525000.000,10359729.000,99832.000,nan,103559793.000,34348384.000,14761694.000,nan,49110078.000,kenneth.lay@enron.com,4273.000,2411.000,36.000,16.000,1.000,123.000
LEFF DANIEL P,273746.000,1000000.000,1387399.000,nan,nan,nan,3083.000,nan,nan,2664228.000,nan,360528.000,nan,360528.000,dan.leff@enron.com,2822.000,2672.000,63.000,14.000,0.000,67.000
LEMAISTRE CHARLES,nan,nan,nan,-25000.000,nan,nan,nan,nan,112492.000,87492.000,412878.000,nan,nan,412878.000,NaN,nan,nan,nan,nan,0.000,nan
LEWIS RICHARD,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,850477.000,nan,nan,850477.000,richard.lewis@enron.com,952.000,739.000,26.000,0.000,0.000,10.000
LINDHOLM TOD A,236457.000,200000.000,175000.000,nan,204075.000,nan,2630.000,57727.000,nan,875889.000,2549361.000,514847.000,nan,3064208.000,tod.lindholm@enron.com,nan,nan,nan,nan,0.000,nan
LOCKHART EUGENE E,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,NaN,nan,nan,nan,nan,0.000,nan
LOWRY CHARLES P,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,372205.000,153686.000,-153686.000,372205.000,NaN,nan,nan,nan,nan,0.000,nan
MARTIN AMANDA K,349487.000,nan,5145434.000,nan,85430.000,nan,2818454.000,8211.000,nan,8407016.000,2070306.000,nan,nan,2070306.000,a..martin@enron.com,1522.000,477.000,230.000,0.000,0.000,8.000
MCCARTY DANNY J,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,664375.000,94556.000,nan,758931.000,danny.mccarty@enron.com,1433.000,508.000,215.000,2.000,0.000,25.000
MCCLELLAN GEORGE,263413.000,900000.000,nan,-125000.000,nan,nan,51587.000,228763.000,nan,1318763.000,506765.000,441096.000,nan,947861.000,george.mcclellan@enron.com,1744.000,1469.000,49.000,0.000,0.000,52.000
MCCONNELL MICHAEL S,365038.000,1100000.000,554422.000,nan,nan,nan,540.000,81364.000,nan,2101364.000,1623010.000,1478269.000,nan,3101279.000,mike.mcconnell@enron.com,3329.000,2189.000,2742.000,194.000,0.000,92.000
MCDONALD REBECCA,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,757301.000,934065.000,nan,1691366.000,rebecca.mcdonald@enron.com,894.000,720.000,13.000,1.000,0.000,54.000
MCMAHON JEFFREY,370448.000,2600000.000,694862.000,nan,nan,nan,297353.000,137108.000,nan,4099771.000,1104054.000,558801.000,nan,1662855.000,jeffrey.mcmahon@enron.com,2355.000,2228.000,48.000,26.000,0.000,58.000
MENDELSOHN JOHN,nan,nan,nan,-103750.000,nan,nan,nan,148.000,103750.000,148.000,nan,nan,nan,nan,NaN,nan,nan,nan,nan,0.000,nan
METTS MARK,365788.000,600000.000,nan,nan,nan,nan,1740.000,94299.000,nan,1061827.000,nan,585062.000,nan,585062.000,mark.metts@enron.com,807.000,702.000,29.000,1.000,0.000,38.000
MEYER JEROME J,nan,nan,nan,-38346.000,nan,nan,nan,2151.000,38346.000,2151.000,nan,nan,nan,nan,NaN,nan,nan,nan,nan,0.000,nan
MEYER ROCKFORD G,nan,nan,nan,nan,1848227.000,nan,nan,nan,nan,1848227.000,493489.000,462384.000,nan,955873.000,rockford.meyer@enron.com,232.000,22.000,28.000,0.000,0.000,0.000
MORAN MICHAEL P,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,59539.000,161602.000,nan,221141.000,michael.moran@enron.com,672.000,127.000,19.000,0.000,0.000,0.000
MORDAUNT KRISTINA M,267093.000,325000.000,nan,nan,nan,nan,1411.000,35018.000,nan,628522.000,nan,208510.000,nan,208510.000,kristina.mordaunt@enron.com,nan,nan,nan,nan,0.000,nan
MULLER MARK S,251654.000,1100000.000,1725545.000,-719000.000,842924.000,nan,947.000,nan,nan,3202070.000,1056320.000,360528.000,nan,1416848.000,s..muller@enron.com,136.000,114.000,16.000,0.000,0.000,12.000
MURRAY JULIA H,229284.000,400000.000,125000.000,nan,nan,nan,330.000,57580.000,nan,812194.000,400478.000,196983.000,nan,597461.000,julia.murray@enron.com,2192.000,395.000,45.000,2.000,0.000,11.000
NOLES JAMES L,nan,nan,nan,nan,774401.000,nan,nan,nan,nan,774401.000,nan,463261.000,-94556.000,368705.000,NaN,nan,nan,nan,nan,0.000,nan
OLSON CINDY K,329078.000,750000.000,100000.000,nan,77716.000,nan,972.000,63791.000,nan,1321557.000,1637034.000,969729.000,nan,2606763.000,cindy.olson@enron.com,1184.000,856.000,52.000,15.000,0.000,20.000
OVERDYKE JR JERE C,94941.000,nan,135836.000,nan,nan,nan,176.000,18834.000,nan,249787.000,5266578.000,2041016.000,nan,7307594.000,jere.overdyke@enron.com,nan,nan,nan,nan,0.000,nan
PAI LOU L,261879.000,1000000.000,nan,nan,nan,nan,1829457.000,32047.000,nan,3123383.000,15364167.000,8453763.000,nan,23817930.000,lou.pai@enron.com,nan,nan,nan,nan,0.000,nan
PEREIRA PAULO V. FERRAZ,nan,nan,nan,-101250.000,nan,nan,nan,27942.000,101250.000,27942.000,nan,nan,nan,nan,NaN,nan,nan,nan,nan,0.000,nan
PICKERING MARK R,655037.000,300000.000,nan,nan,nan,400000.000,nan,31653.000,nan,1386690.000,28798.000,nan,nan,28798.000,mark.pickering@enron.com,898.000,728.000,67.000,0.000,0.000,7.000
PIPER GREGORY F,197091.000,400000.000,nan,-33333.000,1130036.000,nan,778.000,43057.000,nan,1737629.000,880290.000,409554.000,-409554.000,880290.000,greg.piper@enron.com,1238.000,742.000,222.000,48.000,0.000,61.000
PIRO JIM,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,47304.000,nan,47304.000,jim.piro@enron.com,58.000,3.000,16.000,1.000,0.000,0.000
POWERS WILLIAM,nan,nan,nan,-17500.000,nan,nan,nan,nan,17500.000,nan,nan,nan,nan,nan,ken.powers@enron.com,653.000,12.000,26.000,0.000,0.000,0.000
PRENTICE JAMES,nan,nan,nan,nan,564348.000,nan,nan,nan,nan,564348.000,886231.000,208809.000,nan,1095040.000,james.prentice@enron.com,nan,nan,nan,nan,0.000,nan

In [7]:
# Remove the 2 wrong names
data_dict.pop('TOTAL',0)
data_dict.pop('THE TRAVEL AGENCY IN THE PARK',0)

# Remove entry with all NaN data
data_dict.pop('LOCKHART EUGENE E',0)

{'bonus': 'NaN',
 'deferral_payments': 'NaN',
 'deferred_income': 'NaN',
 'director_fees': 'NaN',
 'email_address': 'NaN',
 'exercised_stock_options': 'NaN',
 'expenses': 'NaN',
 'from_messages': 'NaN',
 'from_poi_to_this_person': 'NaN',
 'from_this_person_to_poi': 'NaN',
 'loan_advances': 'NaN',
 'long_term_incentive': 'NaN',
 'other': 'NaN',
 'poi': False,
 'restricted_stock': 'NaN',
 'restricted_stock_deferred': 'NaN',
 'salary': 'NaN',
 'shared_receipt_with_poi': 'NaN',
 'to_messages': 'NaN',
 'total_payments': 'NaN',
 'total_stock_value': 'NaN'}

In [8]:
# update the dataframe

# Formatting for the output:
pd.set_option('display.float_format', lambda x: '%.3f' % x)

# Convert dictionary to DataFrame
enron_df = pd.DataFrame.from_dict(data_dict, orient = 'index', dtype = float)

# reorganize columns
enron_df = enron_df[
['salary',
'bonus',
'long_term_incentive',
'deferred_income',
'deferral_payments',
'loan_advances',
'other',
'expenses',
'director_fees',
'total_payments',
 'exercised_stock_options',
'restricted_stock',
 'restricted_stock_deferred',
 'total_stock_value',
 'email_address',
 'to_messages',
 'shared_receipt_with_poi',
 'from_messages',
 'from_this_person_to_poi',
 'poi',
 'from_poi_to_this_person']]

In [9]:
# second check
enron_df

,salary,bonus,long_term_incentive,deferred_income,deferral_payments,loan_advances,other,expenses,director_fees,total_payments,exercised_stock_options,restricted_stock,restricted_stock_deferred,total_stock_value,email_address,to_messages,shared_receipt_with_poi,from_messages,from_this_person_to_poi,poi,from_poi_to_this_person
ALLEN PHILLIP K,201955.000,4175000.000,304805.000,-3081055.000,2869717.000,nan,152.000,13868.000,nan,4484442.000,1729541.000,126027.000,-126027.000,1729541.000,phillip.allen@enron.com,2902.000,1407.000,2195.000,65.000,0.000,47.000
BADUM JAMES P,nan,nan,nan,nan,178980.000,nan,nan,3486.000,nan,182466.000,257817.000,nan,nan,257817.000,NaN,nan,nan,nan,nan,0.000,nan
BANNANTINE JAMES M,477.000,nan,nan,-5104.000,nan,nan,864523.000,56301.000,nan,916197.000,4046157.000,1757552.000,-560222.000,5243487.000,james.bannantine@enron.com,566.000,465.000,29.000,0.000,0.000,39.000
BAXTER JOHN C,267102.000,1200000.000,1586055.000,-1386055.000,1295738.000,nan,2660303.000,11200.000,nan,5634343.000,6680544.000,3942714.000,nan,10623258.000,NaN,nan,nan,nan,nan,0.000,nan
BAY FRANKLIN R,239671.000,400000.000,nan,-201641.000,260455.000,nan,69.000,129142.000,nan,827696.000,nan,145796.000,-82782.000,63014.000,frank.bay@enron.com,nan,nan,nan,nan,0.000,nan
BAZELIDES PHILIP J,80818.000,nan,93750.000,nan,684694.000,nan,874.000,nan,nan,860136.000,1599641.000,nan,nan,1599641.000,NaN,nan,nan,nan,nan,0.000,nan
BECK SALLY W,231330.000,700000.000,nan,nan,nan,nan,566.000,37172.000,nan,969068.000,nan,126027.000,nan,126027.000,sally.beck@enron.com,7315.000,2639.000,4343.000,386.000,0.000,144.000
BELDEN TIMOTHY N,213999.000,5249999.000,nan,-2334434.000,2144013.000,nan,210698.000,17355.000,nan,5501630.000,953136.000,157569.000,nan,1110705.000,tim.belden@enron.com,7991.000,5521.000,484.000,108.000,1.000,228.000
BELFER ROBERT,nan,nan,nan,nan,-102500.000,nan,nan,nan,3285.000,102500.000,3285.000,nan,44093.000,-44093.000,NaN,nan,nan,nan,nan,0.000,nan
BERBERIAN DAVID,216582.000,nan,nan,nan,nan,nan,nan,11892.000,nan,228474.000,1624396.000,869220.000,nan,2493616.000,david.berberian@enron.com,nan,nan,nan,nan,0.000,nan
BERGSIEKER RICHARD P,187922.000,250000.000,180250.000,-485813.000,nan,nan,427316.000,59175.000,nan,618850.000,nan,659249.000,nan,659249.000,rick.bergsieker@enron.com,383.000,233.000,59.000,0.000,0.000,4.000
BHATNAGAR SANJAY,nan,nan,nan,nan,nan,nan,137864.000,nan,137864.000,15456290.000,2604490.000,-2604490.000,15456290.000,nan,sanjay.bhatnagar@enron.com,523.000,463.000,29.000,1.000,0.000,0.000
BIBI PHILIPPE A,213625.000,1000000.000,369721.000,nan,nan,nan,425688.000,38559.000,nan,2047593.000,1465734.000,378082.000,nan,1843816.000,philippe.bibi@enron.com,1607.000,1336.000,40.000,8.000,0.000,23.000
BLACHMAN JEREMY M,248546.000,850000.000,831809.000,nan,nan,nan,272.000,84208.000,nan,2014835.000,765313.000,189041.000,nan,954354.000,jeremy.blachman@enron.com,2475.000,2326.000,14.000,2.000,0.000,25.000
BLAKE JR. NORMAN P,nan,nan,nan,-113784.000,nan,nan,nan,1279.000,113784.000,1279.000,nan,nan,nan,nan,NaN,nan,nan,nan,nan,0.000,nan
BOWEN JR RAYMOND M,278601.000,1350000.000,974293.000,-833.000,nan,nan,1621.000,65907.000,nan,2669589.000,nan,252055.000,nan,252055.000,raymond.bowen@enron.com,1858.000,1593.000,27.000,15.000,1.000,140.000
BROWN MICHAEL,nan,nan,nan,nan,nan,nan,nan,49288.000,nan,49288.000,nan,nan,nan,nan,michael.brown@enron.com,1486.000,761.000,41.000,1.000,0.000,13.000
BUCHANAN HAROLD G,248017.000,500000.000,304805.000,nan,nan,nan,1215.000,600.000,nan,1054637.000,825464.000,189041.000,nan,1014505.000,john.buchanan@enron.com,1088.000,23.000,125.000,0.000,0.000,0.000
BUTTS ROBERT H,261516.000,750000.000,175000.000,-75000.000,nan,nan,150656.000,9410.000,nan,1271582.000,nan,417619.000,nan,417619.000,bob.butts@enron.com,nan,nan,nan,nan,0.000,nan
BUY RICHARD B,330546.000,900000.000,769862.000,-694862.000,649584.000,nan,400572.000,nan,nan,2355702.000,2542813.000,901657.000,nan,3444470.000,rick.buy@enron.com,3523.000,2333.000,1053.000,71.000,0.000,156.000
CALGER CHRISTOPHER F,240189.000,1250000.000,375304.000,-262500.000,nan,nan,486.000,35818.000,nan,1639297.000,nan,126027.000,nan,126027.000,christopher.calger@enron.com,2598.000,2188.000,144.000,25.000,1.000,199.000
CARTER REBECCA C,261809.000,300000.000,75000.000,-159792.000,nan,nan,540.000,nan,nan,477557.000,nan,307301.000,-307301.000,nan,rebecca.carter@enron.com,312.000,196.000,15.000,7.000,0.000,29.000
CAUSEY RICHARD A,415189.000,1000000.000,350000.000,-235000.000,nan,nan,307895.000,30674.000,nan,1868758.000,nan,2502063.000,nan,2502063.000,richard.causey@enron.com,1892.000,1585.000,49.000,12.000,1.000,58.000
CHAN RONNIE,nan,nan,nan,-98784.000,nan,nan,nan,nan,98784.000,nan,nan,32460.000,-32460.000,nan,NaN,nan,nan,nan,nan,0.000,nan
CHRISTODOULOU DIOMEDES,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,5127155.000,950730.000,nan,6077885.000,diomedes.christodoulou@enron.com,nan,nan,nan,nan,0.000,nan
CLINE KENNETH W,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,662086.000,-472568.000,189518.000,NaN,nan,nan,nan,nan,0.000,nan
COLWELL WESLEY,288542.000,1200000.000,nan,-144062.000,27610.000,nan,101740.000,16514.000,nan,1490344.000,nan,698242.000,nan,698242.000,wes.colwell@enron.com,1758.000,1132.000,40.000,11.000,1.000,240.000
CORDES WILLIAM R,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,651850.000,386335.000,nan,1038185.000,bill.cordes@enron.com,764.000,58.000,12.000,0.000,0.000,10.000
COX DAVID,314288.000,800000.000,nan,-41250.000,nan,nan,494.000,27861.000,nan,1101393.000,117551.000,378082.000,nan,495633.000,chip.cox@enron.com,102.000,71.000,33.000,4.000,0.000,0.000
CUMBERLAND MICHAEL S,184899.000,325000.000,275000.000,nan,nan,nan,713.000,22344.000,nan,807956.000,nan,207940.000,nan,207940.000,NaN,nan,nan,nan,nan,0.000,nan
DEFFNER JOSEPH M,206121.000,600000.000,335349.000,nan,nan,nan,25553.000,41626.000,nan,1208649.000,17378.000,141833.000,nan,159211.000,joseph.deffner@enron.com,714.000,552.000,74.000,4.000,0.000,115.000
DELAINEY DAVID W,365163.000,3000000.000,1294981.000,nan,nan,nan,1661.000,86174.000,nan,4747979.000,2291113.000,1323148.000,nan,3614261.000,david.delainey@enron.com,3093.000,2097.000,3069.000,609.000,1.000,66.000
DERRICK JR. JAMES V,492375.000,800000.000,484000.000,-1284000.000,nan,nan,7482.000,51124.000,nan,550981.000,8831913.000,1787380.000,-1787380.000,8831913.000,james.derrick@enron.com,2181.000,1401.000,909.000,20.000,0.000,64.000
DETMERING TIMOTHY J,210500.000,425000.000,415657.000,-775241.000,875307.000,nan,1105.000,52255.000,nan,1204583.000,2027865.000,315068.000,-315068.000,2027865.000,timothy.detmering@enron.com,nan,nan,nan,nan,0.000,nan
DIETRICH JANET R,250100.000,600000.000,556416.000,nan,nan,nan,473.000,3475.000,nan,1410464.000,1550019.000,315068.000,nan,1865087.000,janet.dietrich@enron.com,2572.000,1902.000,63.000,14.000,0.000,305.000
DIMICHELE RICHARD G,262788.000,1000000.000,694862.000,nan,nan,nan,374689.000,35812.000,nan,2368151.000,8191755.000,126027.000,nan,8317782.000,richard.dimichele@enron.com,nan,nan,nan,nan,0.000,nan
DODSON KEITH,221003.000,70000.000,nan,nan,nan,nan,774.000,28164.000,nan,319941.000,nan,nan,nan,nan,keith.dodson@enron.com,176.000,114.000,14.000,3.000,0.000,10.000
DONAHUE JR JEFFREY M,278601.000,800000.000,nan,-300000.000,nan,nan,891.000,96268.000,nan,875760.000,765920.000,315068.000,nan,1080988.000,jeff.donahue@enron.com,865.000,772.000,22.000,11.000,0.000,188.000
DUNCAN JOHN H,nan,nan,nan,-25000.000,nan,nan,nan,nan,102492.000,77492.000,371750.000,nan,nan,371750.000,NaN,nan,nan,nan,nan,0.000,nan
DURAN WILLIAM D,210692.000,750000.000,1105218.000,nan,nan,nan,1568.000,25785.000,nan,2093263.000,1451869.000,189041.000,nan,1640910.000,w.duran@enron.com,904.000,599.000,12.000,3.000,0.000,106.000
ECHOLS JOHN B,182245.000,200000.000,2234774.000,nan,nan,nan,53775.000,21530.000,nan,2692324.000,601438.000,407503.000,nan,1008941.000,john.echols@enron.com,nan,nan,nan,nan,0.000,nan
ELLIOTT STEVEN,170941.000,350000.000,nan,-400729.000,nan,nan,12961.000,78552.000,nan,211725.000,4890344.000,1788391.000,nan,6678735.000,steven.elliott@enron.com,nan,nan,nan,nan,0.000,nan
FALLON JAMES B,304588.000,2500000.000,374347.000,nan,nan,nan,401481.000,95924.000,nan,3676340.000,940257.000,1392142.000,nan,2332399.000,jim.fallon@enron.com,1755.000,1604.000,75.000,37.000,0.000,42.000
FASTOW ANDREW S,440698.000,1300000.000,1736055.000,-1386055.000,nan,nan,277464.000,55921.000,nan,2424083.000,nan,1794412.000,nan,1794412.000,andrew.fastow@enron.com,nan,nan,nan,nan,1.000,nan
FITZGERALD JAY L,199157.000,350000.000,556416.000,nan,nan,nan,285414.000,23870.000,nan,1414857.000,664461.000,956775.000,nan,1621236.000,jay.fitzgerald@enron.com,936.000,723.000,16.000,8.000,0.000,1.000
FOWLER PEGGY,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1324578.000,560170.000,nan,1884748.000,kulvinder.fowler@enron.com,517.000,10.000,36.000,0.000,0.000,0.000
FOY JOE,nan,nan,nan,nan,181755.000,nan,nan,nan,nan,181755.000,343434.000,nan,nan,343434.000,tracy.foy@enron.com,57.000,2.000,13.000,0.000,0.000,0.000
FREVERT MARK A,1060932.000,2000000.000,1617011.000,-3367011.000,6426990.000,2000000.000,7427621.000,86987.000,nan,17252530.000,10433518.000,4188667.000,nan,14622185.000,mark.frevert@enron.com,3275.000,2979.000,21.000,6.000,0.000,242.000
FUGH JOHN L,nan,nan,nan,nan,50591.000,nan,nan,nan,nan,50591.000,176378.000,nan,nan,176378.000,NaN,nan,nan,nan,nan,0.000,nan
GAHN ROBERT S,192008.000,509870.000,nan,-1042.000,73122.000,nan,76547.000,50080.000,nan,900585.000,83237.000,235370.000,nan,318607.000,NaN,nan,nan,nan,nan,0.000,nan
GARLAND C KEVIN,231946.000,850000.000,375304.000,nan,nan,nan,60814.000,48405.000,nan,1566469.000,636246.000,259907.000,nan,896153.000,kevin.garland@enron.com,209.000,178.000,44.000,27.000,0.000,10.000
GATHMANN WILLIAM D,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1753766.000,264013.000,-72419.000,1945360.000,NaN,nan,nan,nan,nan,0.000,nan
GIBBS DANA R,nan,nan,461912.000,nan,504610.000,nan,nan,nan,nan,966522.000,2218275.000,nan,nan,2218275.000,dana.gibbs@enron.com,169.000,23.000,12.000,0.000,0.000,0.000
GILLIS JOHN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,9803.000,75838.000,nan,85641.000,NaN,nan,nan,nan,nan,0.000,nan
GLISAN JR BEN F,274975.000,600000.000,71023.000,nan,nan,nan,200308.000,125978.000,nan,1272284.000,384728.000,393818.000,nan,778546.000,ben.glisan@enron.com,873.000,874.000,16.000,6.000,1.000,52.000
GOLD JOSEPH,272880.000,750000.000,304805.000,nan,nan,nan,819288.000,nan,nan,2146973.000,436515.000,441096.000,nan,877611.000,joe.gold@enron.com,nan,nan,nan,nan,0.000,nan
GRAMM WENDY L,nan,nan,nan,nan,nan,nan,nan,nan,119292.000,119292.000,nan,nan,nan,nan,NaN,nan,nan,nan,nan,0.000,nan
GRAY RODNEY,6615.000,nan,365625.000,nan,93585.000,nan,680833.000,nan,nan,1146658.000,nan,nan,nan,nan,NaN,nan,nan,nan,nan,0.000,nan
HAEDICKE MARK E,374125.000,1150000.000,983346.000,-934484.000,2157527.000,nan,52382.000,76169.000,nan,3859065.000,608750.000,524169.000,-329825.000,803094.000,mark.haedicke@enron.com,4009.000,1847.000,1941.000,61.000,0.000,180.000
HANNON KEVIN P,243293.000,1500000.000,1617011.000,-3117011.000,nan,nan,11350.000,34039.000,nan,288682.000,5538001.000,853064.000,nan,6391065.000,kevin.hannon@enron.com,1045.000,1035.000,32.000,21.000,1.000,32.000
HAUG DAVID L,nan,nan,nan,nan,nan,nan,nan,475.000,nan,475.000,nan,2217299.000,nan,2217299.000,david.haug@enron.com,573.000,471.000,19.000,7.000,0.000,4.000
HAYES ROBERT E,nan,nan,nan,nan,7961.000,nan,nan,nan,nan,7961.000,nan,151418.000,nan,151418.000,robert.hayes@enron.com,504.000,50.000,12.000,0.000,0.000,16.000
HAYSLETT RODERICK J,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,346663.000,nan,346663.000,rod.hayslett@enron.com,2649.000,571.000,1061.000,38.000,0.000,35.000
HERMANN ROBERT J,262663.000,700000.000,150000.000,-280000.000,nan,nan,416441.000,48357.000,nan,1297461.000,187500.000,480632.000,nan,668132.000,robert.hermann@enron.com,nan,nan,nan,nan,0.000,nan
HICKERSON GARY J,211788.000,1700000.000,69223.000,nan,nan,nan,1936.000,98849.000,nan,2081796.000,nan,441096.000,nan,441096.000,gary.hickerson@enron.com,1320.000,900.000,27.000,1.000,0.000,40.000
HIRKO JOSEPH,nan,nan,nan,nan,10259.000,nan,2856.000,77978.000,nan,91093.000,30766064.000,nan,nan,30766064.000,joe.hirko@enron.com,nan,nan,nan,nan,1.000,nan
HORTON STANLEY C,nan,nan,nan,nan,3131860.000,nan,nan,nan,nan,3131860.000,5210569.000,2046079.000,nan,7256648.000,stanley.horton@enron.com,2350.000,1074.000,1073.000,15.000,0.000,44.000
HUGHES JAMES A,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,754966.000,363428.000,nan,1118394.000,james.hughes@enron.com,719.000,589.000,34.000,5.000,0.000,35.000
HUMPHREY GENE E,130724.000,nan,nan,nan,2964506.000,nan,nan,4994.000,nan,3100224.000,2282768.000,nan,nan,2282768.000,gene.humphrey@enron.com,128.000,119.000,17.000,17.000,0.000,10.000
IZZO LAWRENCE L,85274.000,nan,312500.000,nan,nan,nan,1553729.000,28093.000,nan,1979596.000,2165172.000,3654808.000,nan,5819980.000,larry.izzo@enron.com,496.000,437.000,19.000,5.000,0.000,28.000
JACKSON CHARLENE R,288558.000,250000.000,nan,nan,nan,nan,2435.000,10181.000,nan,551174.000,185063.000,540672.000,nan,725735.000,charlene.jackson@enron.com,258.000,117.000,56.000,19.000,0.000,25.000
JAEDICKE ROBERT,nan,nan,nan,-25000.000,nan,nan,nan,nan,108750.000,83750.000,431750.000,44093.000,-44093.000,431750.000,NaN,nan,nan,nan,nan,0.000,nan
KAMINSKI WINCENTY J,275101.000,400000.000,323466.000,nan,nan,nan,4669.000,83585.000,nan,1086821.000,850010.000,126027.000,nan,976037.000,vince.kaminski@enron.com,4607.000,583.000,14368.000,171.000,0.000,41.000
KEAN STEVEN J,404338.000,1000000.000,300000.000,nan,nan,nan,1231.000,41953.000,nan,1747522.000,2022048.000,4131594.000,nan,6153642.000,steven.kean@enron.com,12754.000,3639.000,6759.000,387.000,0.000,140.000
KISHKILL JOSEPH G,174246.000,nan,nan,-51042.000,nan,nan,465357.000,116335.000,nan,704896.000,nan,1034346.000,nan,1034346.000,joe.kishkill@enron.com,nan,nan,nan,nan,0.000,nan
KITCHEN LOUISE,271442.000,3100000.000,nan,nan,nan,nan,93925.000,5774.000,nan,3471141.000,81042.000,466101.000,nan,547143.000,louise.kitchen@enron.com,8305.000,3669.000,1728.000,194.000,0.000,251.000
KOENIG MARK E,309946.000,700000.000,300000.000,nan,nan,nan,150458.000,127017.000,nan,1587421.000,671737.000,1248318.000,nan,1920055.000,mark.koenig@enron.com,2374.000,2271.000,61.000,15.000,1.000,53.000
KOPPER MICHAEL J,224305.000,800000.000,602671.000,nan,nan,nan,907502.000,118134.000,nan,2652612.000,nan,985032.000,nan,985032.000,michael.kopper@enron.com,nan,nan,nan,nan,1.000,nan
LAVORATO JOHN J,339288.000,8000000.000,2035380.000,nan,nan,nan,1552.000,49537.000,nan,10425757.000,4158995.000,1008149.000,nan,5167144.000,john.lavorato@enron.com,7259.000,3962.000,2585.000,411.000,0.000,528.000
LAY KENNETH L,1072321.000,7000000.000,3600000.000,-300000.000,202911.000,81525000.000,10359729.000,99832.000,nan,103559793.000,34348384.000,14761694.000,nan,49110078.000,kenneth.lay@enron.com,4273.000,2411.000,36.000,16.000,1.000,123.000
LEFF DANIEL P,273746.000,1000000.000,1387399.000,nan,nan,nan,3083.000,nan,nan,2664228.000,nan,360528.000,nan,360528.000,dan.leff@enron.com,2822.000,2672.000,63.000,14.000,0.000,67.000
LEMAISTRE CHARLES,nan,nan,nan,-25000.000,nan,nan,nan,nan,112492.000,87492.000,412878.000,nan,nan,412878.000,NaN,nan,nan,nan,nan,0.000,nan
LEWIS RICHARD,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,850477.000,nan,nan,850477.000,richard.lewis@enron.com,952.000,739.000,26.000,0.000,0.000,10.000
LINDHOLM TOD A,236457.000,200000.000,175000.000,nan,204075.000,nan,2630.000,57727.000,nan,875889.000,2549361.000,514847.000,nan,3064208.000,tod.lindholm@enron.com,nan,nan,nan,nan,0.000,nan
LOWRY CHARLES P,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,372205.000,153686.000,-153686.000,372205.000,NaN,nan,nan,nan,nan,0.000,nan
MARTIN AMANDA K,349487.000,nan,5145434.000,nan,85430.000,nan,2818454.000,8211.000,nan,8407016.000,2070306.000,nan,nan,2070306.000,a..martin@enron.com,1522.000,477.000,230.000,0.000,0.000,8.000
MCCARTY DANNY J,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,664375.000,94556.000,nan,758931.000,danny.mccarty@enron.com,1433.000,508.000,215.000,2.000,0.000,25.000
MCCLELLAN GEORGE,263413.000,900000.000,nan,-125000.000,nan,nan,51587.000,228763.000,nan,1318763.000,506765.000,441096.000,nan,947861.000,george.mcclellan@enron.com,1744.000,1469.000,49.000,0.000,0.000,52.000
MCCONNELL MICHAEL S,365038.000,1100000.000,554422.000,nan,nan,nan,540.000,81364.000,nan,2101364.000,1623010.000,1478269.000,nan,3101279.000,mike.mcconnell@enron.com,3329.000,2189.000,2742.000,194.000,0.000,92.000
MCDONALD REBECCA,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,757301.000,934065.000,nan,1691366.000,rebecca.mcdonald@enron.com,894.000,720.000,13.000,1.000,0.000,54.000
MCMAHON JEFFREY,370448.000,2600000.000,694862.000,nan,nan,nan,297353.000,137108.000,nan,4099771.000,1104054.000,558801.000,nan,1662855.000,jeffrey.mcmahon@enron.com,2355.000,2228.000,48.000,26.000,0.000,58.000
MENDELSOHN JOHN,nan,nan,nan,-103750.000,nan,nan,nan,148.000,103750.000,148.000,nan,nan,nan,nan,NaN,nan,nan,nan,nan,0.000,nan
METTS MARK,365788.000,600000.000,nan,nan,nan,nan,1740.000,94299.000,nan,1061827.000,nan,585062.000,nan,585062.000,mark.metts@enron.com,807.000,702.000,29.000,1.000,0.000,38.000
MEYER JEROME J,nan,nan,nan,-38346.000,nan,nan,nan,2151.000,38346.000,2151.000,nan,nan,nan,nan,NaN,nan,nan,nan,nan,0.000,nan
MEYER ROCKFORD G,nan,nan,nan,nan,1848227.000,nan,nan,nan,nan,1848227.000,493489.000,462384.000,nan,955873.000,rockford.meyer@enron.com,232.000,22.000,28.000,0.000,0.000,0.000
MORAN MICHAEL P,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,59539.000,161602.000,nan,221141.000,michael.moran@enron.com,672.000,127.000,19.000,0.000,0.000,0.000
MORDAUNT KRISTINA M,267093.000,325000.000,nan,nan,nan,nan,1411.000,35018.000,nan,628522.000,nan,208510.000,nan,208510.000,kristina.mordaunt@enron.com,nan,nan,nan,nan,0.000,nan
MULLER MARK S,251654.000,1100000.000,1725545.000,-719000.000,842924.000,nan,947.000,nan,nan,3202070.000,1056320.000,360528.000,nan,1416848.000,s..muller@enron.com,136.000,114.000,16.000,0.000,0.000,12.000
MURRAY JULIA H,229284.000,400000.000,125000.000,nan,nan,nan,330.000,57580.000,nan,812194.000,400478.000,196983.000,nan,597461.000,julia.murray@enron.com,2192.000,395.000,45.000,2.000,0.000,11.000
NOLES JAMES L,nan,nan,nan,nan,774401.000,nan,nan,nan,nan,774401.000,nan,463261.000,-94556.000,368705.000,NaN,nan,nan,nan,nan,0.000,nan
OLSON CINDY K,329078.000,750000.000,100000.000,nan,77716.000,nan,972.000,63791.000,nan,1321557.000,1637034.000,969729.000,nan,2606763.000,cindy.olson@enron.com,1184.000,856.000,52.000,15.000,0.000,20.000
OVERDYKE JR JERE C,94941.000,nan,135836.000,nan,nan,nan,176.000,18834.000,nan,249787.000,5266578.000,2041016.000,nan,7307594.000,jere.overdyke@enron.com,nan,nan,nan,nan,0.000,nan
PAI LOU L,261879.000,1000000.000,nan,nan,nan,nan,1829457.000,32047.000,nan,3123383.000,15364167.000,8453763.000,nan,23817930.000,lou.pai@enron.com,nan,nan,nan,nan,0.000,nan
PEREIRA PAULO V. FERRAZ,nan,nan,nan,-101250.000,nan,nan,nan,27942.000,101250.000,27942.000,nan,nan,nan,nan,NaN,nan,nan,nan,nan,0.000,nan
PICKERING MARK R,655037.000,300000.000,nan,nan,nan,400000.000,nan,31653.000,nan,1386690.000,28798.000,nan,nan,28798.000,mark.pickering@enron.com,898.000,728.000,67.000,0.000,0.000,7.000
PIPER GREGORY F,197091.000,400000.000,nan,-33333.000,1130036.000,nan,778.000,43057.000,nan,1737629.000,880290.000,409554.000,-409554.000,880290.000,greg.piper@enron.com,1238.000,742.000,222.000,48.000,0.000,61.000
PIRO JIM,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,47304.000,nan,47304.000,jim.piro@enron.com,58.000,3.000,16.000,1.000,0.000,0.000
POWERS WILLIAM,nan,nan,nan,-17500.000,nan,nan,nan,nan,17500.000,nan,nan,nan,nan,nan,ken.powers@enron.com,653.000,12.000,26.000,0.000,0.000,0.000
PRENTICE JAMES,nan,nan,nan,nan,564348.000,nan,nan,nan,nan,564348.000,886231.000,208809.000,nan,1095040.000,james.prentice@enron.com,nan,nan,nan,nan,0.000,nan

In [10]:
# Counting the POIs
print("number of poi: {}".format(enron_df[enron_df['poi']==True]['poi'].count()))

number of poi: 18

In [11]:
# Counting the NON-POIs
print("number of non_poi: {}".format(enron_df[enron_df['poi']==False]['poi'].count()))

number of non_poi: 125

In [12]:
# print the POIs
index = enron_df.index

condition_poi = enron_df["poi"] == True


person_poi = index[condition_poi]


person_poi_list = person_poi.tolist()


print ('\n'.join(map(str, person_poi_list)))

BELDEN TIMOTHY N
BOWEN JR RAYMOND M
CALGER CHRISTOPHER F
CAUSEY RICHARD A
COLWELL WESLEY
DELAINEY DAVID W
FASTOW ANDREW S
GLISAN JR BEN F
HANNON KEVIN P
HIRKO JOSEPH
KOENIG MARK E
KOPPER MICHAEL J
LAY KENNETH L
RICE KENNETH D
RIEKER PAULA H
SHELBY REX
SKILLING JEFFREY K
YEAGER F SCOTT

In [13]:
# Change the NaN to 0

enron_df = enron_df.fillna(0)
enron_df.head()

,salary,bonus,long_term_incentive,deferred_income,deferral_payments,loan_advances,other,expenses,director_fees,total_payments,exercised_stock_options,restricted_stock,restricted_stock_deferred,total_stock_value,email_address,to_messages,shared_receipt_with_poi,from_messages,from_this_person_to_poi,poi,from_poi_to_this_person
ALLEN PHILLIP K,201955.000,4175000.000,304805.000,-3081055.000,2869717.000,0.000,152.000,13868.000,0.000,4484442.000,1729541.000,126027.000,-126027.000,1729541.000,phillip.allen@enron.com,2902.000,1407.000,2195.000,65.000,0.000,47.000
BADUM JAMES P,0.000,0.000,0.000,0.000,178980.000,0.000,0.000,3486.000,0.000,182466.000,257817.000,0.000,0.000,257817.000,NaN,0.000,0.000,0.000,0.000,0.000,0.000
BANNANTINE JAMES M,477.000,0.000,0.000,-5104.000,0.000,0.000,864523.000,56301.000,0.000,916197.000,4046157.000,1757552.000,-560222.000,5243487.000,james.bannantine@enron.com,566.000,465.000,29.000,0.000,0.000,39.000
BAXTER JOHN C,267102.000,1200000.000,1586055.000,-1386055.000,1295738.000,0.000,2660303.000,11200.000,0.000,5634343.000,6680544.000,3942714.000,0.000,10623258.000,NaN,0.000,0.000,0.000,0.000,0.000,0.000
BAY FRANKLIN R,239671.000,400000.000,0.000,-201641.000,260455.000,0.000,69.000,129142.000,0.000,827696.000,0.000,145796.000,-82782.000,63014.000,frank.bay@enron.com,0.000,0.000,0.000,0.000,0.000,0.000

In [14]:
# dataframe stats

enron_df.describe()

,salary,bonus,long_term_incentive,deferred_income,deferral_payments,loan_advances,other,expenses,director_fees,total_payments,exercised_stock_options,restricted_stock,restricted_stock_deferred,total_stock_value,to_messages,shared_receipt_with_poi,from_messages,from_this_person_to_poi,poi,from_poi_to_this_person
count,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000
mean,186742.860,680724.608,339314.182,-195037.699,223642.629,586888.112,296806.692,35622.720,10050.112,2272322.587,2090318.077,874609.972,73931.315,2930133.762,1247.217,707.524,366.126,24.797,0.126,39.028
std,197117.072,1236179.688,689013.933,607922.475,756520.789,6818177.362,1135030.646,45370.870,31399.349,8876252.372,4809193.249,2022338.365,1306545.168,6205936.524,2243.006,1079.457,1455.452,80.032,0.333,74.466
min,0.000,0.000,0.000,-3504386.000,-102500.000,0.000,0.000,0.000,0.000,0.000,0.000,-2604490.000,-1787380.000,-44093.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,0.000,0.000,0.000,-37506.000,0.000,0.000,0.000,0.000,0.000,96796.500,0.000,38276.500,0.000,254936.000,0.000,0.000,0.000,0.000,0.000,0.000
50%,210692.000,300000.000,0.000,0.000,0.000,0.000,947.000,21530.000,0.000,966522.000,608750.000,360528.000,0.000,976037.000,383.000,114.000,18.000,0.000,0.000,4.000
75%,270259.000,800000.000,374825.500,0.000,9110.000,0.000,149204.000,53534.500,0.000,1956977.500,1698900.500,775992.000,0.000,2307583.500,1639.000,967.500,54.000,14.000,0.000,41.500
max,1111258.000,8000000.000,5145434.000,0.000,6426990.000,81525000.000,10359729.000,228763.000,137864.000,103559793.000,34348384.000,14761694.000,15456290.000,49110078.000,15149.000,5521.000,14368.000,609.000,1.000,528.000

why is deferral_payments negative, who is doing this?

In [15]:
# print rows with deferral_payments < 0
index = enron_df.index

condition = enron_df["deferral_payments"]<0

person_ind = index[condition]

person_ind_list = person_ind.tolist()

print (person_ind_list)

['BELFER ROBERT']

In [16]:
# lets see more about his person

enron_df.loc['BELFER ROBERT']

salary                            0.000
bonus                             0.000
long_term_incentive               0.000
deferred_income                   0.000
deferral_payments           -102500.000
loan_advances                     0.000
other                             0.000
expenses                          0.000
director_fees                  3285.000
total_payments               102500.000
exercised_stock_options        3285.000
restricted_stock                  0.000
restricted_stock_deferred     44093.000
total_stock_value            -44093.000
email_address                       NaN
to_messages                       0.000
shared_receipt_with_poi           0.000
from_messages                     0.000
from_this_person_to_poi           0.000
poi                               0.000
from_poi_to_this_person           0.000
Name: BELFER ROBERT, dtype: object

Looks like the data was not imported properly and the columns shifted. 
Deferred income should have been -102500.00 not deferral_payments.
let's see if this hapened anywhere else.

In [17]:
# add columns to check that valeus are correct for 
# total_payments and total_stock

enron_df['add_total_payments'] = \
enron_df['salary'] + \
enron_df['bonus'] + \
enron_df['long_term_incentive'] + \
enron_df['deferred_income'] + \
enron_df['deferral_payments'] + \
enron_df['loan_advances'] + \
enron_df['other'] +  \
enron_df['expenses'] + \
enron_df['director_fees'] 

enron_df['add_total_stock'] = \
enron_df['exercised_stock_options'] + \
enron_df['restricted_stock'] + \
enron_df['restricted_stock_deferred'] 


enron_df['check_total_payments'] = enron_df['add_total_payments'] == enron_df['total_payments']
enron_df['check_total_stock'] = enron_df['add_total_stock'] == enron_df['total_stock_value']

In [18]:
# Check total_payments
enron_df[enron_df['check_total_payments']==0]

,salary,bonus,long_term_incentive,deferred_income,deferral_payments,loan_advances,other,expenses,director_fees,total_payments,exercised_stock_options,restricted_stock,restricted_stock_deferred,total_stock_value,email_address,to_messages,shared_receipt_with_poi,from_messages,from_this_person_to_poi,poi,from_poi_to_this_person,add_total_payments,add_total_stock,check_total_payments,check_total_stock
BELFER ROBERT,0.000,0.000,0.000,0.000,-102500.000,0.000,0.000,0.000,3285.000,102500.000,3285.000,0.000,44093.000,-44093.000,NaN,0.000,0.000,0.000,0.000,0.000,0.000,-99215.000,47378.000,False,False
BHATNAGAR SANJAY,0.000,0.000,0.000,0.000,0.000,0.000,137864.000,0.000,137864.000,15456290.000,2604490.000,-2604490.000,15456290.000,0.000,sanjay.bhatnagar@enron.com,523.000,463.000,29.000,1.000,0.000,0.000,275728.000,15456290.000,False,False

In [19]:
# Check total stock
enron_df[enron_df['check_total_stock']==0]

,salary,bonus,long_term_incentive,deferred_income,deferral_payments,loan_advances,other,expenses,director_fees,total_payments,exercised_stock_options,restricted_stock,restricted_stock_deferred,total_stock_value,email_address,to_messages,shared_receipt_with_poi,from_messages,from_this_person_to_poi,poi,from_poi_to_this_person,add_total_payments,add_total_stock,check_total_payments,check_total_stock
BELFER ROBERT,0.000,0.000,0.000,0.000,-102500.000,0.000,0.000,0.000,3285.000,102500.000,3285.000,0.000,44093.000,-44093.000,NaN,0.000,0.000,0.000,0.000,0.000,0.000,-99215.000,47378.000,False,False
BHATNAGAR SANJAY,0.000,0.000,0.000,0.000,0.000,0.000,137864.000,0.000,137864.000,15456290.000,2604490.000,-2604490.000,15456290.000,0.000,sanjay.bhatnagar@enron.com,523.000,463.000,29.000,1.000,0.000,0.000,275728.000,15456290.000,False,False

In [20]:
# Let's look at the other person's data
enron_df.loc['BHATNAGAR SANJAY']

salary                                            0.000
bonus                                             0.000
long_term_incentive                               0.000
deferred_income                                   0.000
deferral_payments                                 0.000
loan_advances                                     0.000
other                                        137864.000
expenses                                          0.000
director_fees                                137864.000
total_payments                             15456290.000
exercised_stock_options                     2604490.000
restricted_stock                           -2604490.000
restricted_stock_deferred                  15456290.000
total_stock_value                                 0.000
email_address                sanjay.bhatnagar@enron.com
to_messages                                     523.000
shared_receipt_with_poi                         463.000
from_messages                                    29.000
from_this_person_to_poi                           1.000
poi                                               0.000
from_poi_to_this_person                           0.000
add_total_payments                           275728.000
add_total_stock                            15456290.000
check_total_payments                              False
check_total_stock                                 False
Name: BHATNAGAR SANJAY, dtype: object

In [21]:
# Fix the 2 shifted person entries
from support_functions  import *

# Fix shifted data function
fix_shifted_data(data_dict)

{'ALLEN PHILLIP K': {'bonus': 4175000,
  'deferral_payments': 2869717,
  'deferred_income': -3081055,
  'director_fees': 'NaN',
  'email_address': 'phillip.allen@enron.com',
  'exercised_stock_options': 1729541,
  'expenses': 13868,
  'from_messages': 2195,
  'from_poi_to_this_person': 47,
  'from_this_person_to_poi': 65,
  'loan_advances': 'NaN',
  'long_term_incentive': 304805,
  'other': 152,
  'poi': False,
  'restricted_stock': 126027,
  'restricted_stock_deferred': -126027,
  'salary': 201955,
  'shared_receipt_with_poi': 1407,
  'to_messages': 2902,
  'total_payments': 4484442,
  'total_stock_value': 1729541},
 'BADUM JAMES P': {'bonus': 'NaN',
  'deferral_payments': 178980,
  'deferred_income': 'NaN',
  'director_fees': 'NaN',
  'email_address': 'NaN',
  'exercised_stock_options': 257817,
  'expenses': 3486,
  'from_messages': 'NaN',
  'from_poi_to_this_person': 'NaN',
  'from_this_person_to_poi': 'NaN',
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 'NaN',
  'poi': False,
  'restricted_stock': 'NaN',
  'restricted_stock_deferred': 'NaN',
  'salary': 'NaN',
  'shared_receipt_with_poi': 'NaN',
  'to_messages': 'NaN',
  'total_payments': 182466,
  'total_stock_value': 257817},
 'BANNANTINE JAMES M': {'bonus': 'NaN',
  'deferral_payments': 'NaN',
  'deferred_income': -5104,
  'director_fees': 'NaN',
  'email_address': 'james.bannantine@enron.com',
  'exercised_stock_options': 4046157,
  'expenses': 56301,
  'from_messages': 29,
  'from_poi_to_this_person': 39,
  'from_this_person_to_poi': 0,
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 864523,
  'poi': False,
  'restricted_stock': 1757552,
  'restricted_stock_deferred': -560222,
  'salary': 477,
  'shared_receipt_with_poi': 465,
  'to_messages': 566,
  'total_payments': 916197,
  'total_stock_value': 5243487},
 'BAXTER JOHN C': {'bonus': 1200000,
  'deferral_payments': 1295738,
  'deferred_income': -1386055,
  'director_fees': 'NaN',
  'email_address': 'NaN',
  'exercised_stock_options': 6680544,
  'expenses': 11200,
  'from_messages': 'NaN',
  'from_poi_to_this_person': 'NaN',
  'from_this_person_to_poi': 'NaN',
  'loan_advances': 'NaN',
  'long_term_incentive': 1586055,
  'other': 2660303,
  'poi': False,
  'restricted_stock': 3942714,
  'restricted_stock_deferred': 'NaN',
  'salary': 267102,
  'shared_receipt_with_poi': 'NaN',
  'to_messages': 'NaN',
  'total_payments': 5634343,
  'total_stock_value': 10623258},
 'BAY FRANKLIN R': {'bonus': 400000,
  'deferral_payments': 260455,
  'deferred_income': -201641,
  'director_fees': 'NaN',
  'email_address': 'frank.bay@enron.com',
  'exercised_stock_options': 'NaN',
  'expenses': 129142,
  'from_messages': 'NaN',
  'from_poi_to_this_person': 'NaN',
  'from_this_person_to_poi': 'NaN',
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 69,
  'poi': False,
  'restricted_stock': 145796,
  'restricted_stock_deferred': -82782,
  'salary': 239671,
  'shared_receipt_with_poi': 'NaN',
  'to_messages': 'NaN',
  'total_payments': 827696,
  'total_stock_value': 63014},
 'BAZELIDES PHILIP J': {'bonus': 'NaN',
  'deferral_payments': 684694,
  'deferred_income': 'NaN',
  'director_fees': 'NaN',
  'email_address': 'NaN',
  'exercised_stock_options': 1599641,
  'expenses': 'NaN',
  'from_messages': 'NaN',
  'from_poi_to_this_person': 'NaN',
  'from_this_person_to_poi': 'NaN',
  'loan_advances': 'NaN',
  'long_term_incentive': 93750,
  'other': 874,
  'poi': False,
  'restricted_stock': 'NaN',
  'restricted_stock_deferred': 'NaN',
  'salary': 80818,
  'shared_receipt_with_poi': 'NaN',
  'to_messages': 'NaN',
  'total_payments': 860136,
  'total_stock_value': 1599641},
 'BECK SALLY W': {'bonus': 700000,
  'deferral_payments': 'NaN',
  'deferred_income': 'NaN',
  'director_fees': 'NaN',
  'email_address': 'sally.beck@enron.com',
  'exercised_stock_options': 'NaN',
  'expenses': 37172,
  'from_messages': 4343,
  'from_poi_to_this_person': 144,
  'from_this_person_to_poi': 386,
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 566,
  'poi': False,
  'restricted_stock': 126027,
  'restricted_stock_deferred': 'NaN',
  'salary': 231330,
  'shared_receipt_with_poi': 2639,
  'to_messages': 7315,
  'total_payments': 969068,
  'total_stock_value': 126027},
 'BELDEN TIMOTHY N': {'bonus': 5249999,
  'deferral_payments': 2144013,
  'deferred_income': -2334434,
  'director_fees': 'NaN',
  'email_address': 'tim.belden@enron.com',
  'exercised_stock_options': 953136,
  'expenses': 17355,
  'from_messages': 484,
  'from_poi_to_this_person': 228,
  'from_this_person_to_poi': 108,
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 210698,
  'poi': True,
  'restricted_stock': 157569,
  'restricted_stock_deferred': 'NaN',
  'salary': 213999,
  'shared_receipt_with_poi': 5521,
  'to_messages': 7991,
  'total_payments': 5501630,
  'total_stock_value': 1110705},
 'BELFER ROBERT': {'bonus': 'NaN',
  'deferral_payments': 'NaN',
  'deferred_income': -102500,
  'director_fees': 102500,
  'email_address': 'NaN',
  'exercised_stock_options': 'NaN',
  'expenses': 3285,
  'from_messages': 'NaN',
  'from_poi_to_this_person': 'NaN',
  'from_this_person_to_poi': 'NaN',
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 'NaN',
  'poi': False,
  'restricted_stock': 44093,
  'restricted_stock_deferred': -44093,
  'salary': 'NaN',
  'shared_receipt_with_poi': 'NaN',
  'to_messages': 'NaN',
  'total_payments': 3285,
  'total_stock_value': 'NaN'},
 'BERBERIAN DAVID': {'bonus': 'NaN',
  'deferral_payments': 'NaN',
  'deferred_income': 'NaN',
  'director_fees': 'NaN',
  'email_address': 'david.berberian@enron.com',
  'exercised_stock_options': 1624396,
  'expenses': 11892,
  'from_messages': 'NaN',
  'from_poi_to_this_person': 'NaN',
  'from_this_person_to_poi': 'NaN',
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 'NaN',
  'poi': False,
  'restricted_stock': 869220,
  'restricted_stock_deferred': 'NaN',
  'salary': 216582,
  'shared_receipt_with_poi': 'NaN',
  'to_messages': 'NaN',
  'total_payments': 228474,
  'total_stock_value': 2493616},
 'BERGSIEKER RICHARD P': {'bonus': 250000,
  'deferral_payments': 'NaN',
  'deferred_income': -485813,
  'director_fees': 'NaN',
  'email_address': 'rick.bergsieker@enron.com',
  'exercised_stock_options': 'NaN',
  'expenses': 59175,
  'from_messages': 59,
  'from_poi_to_this_person': 4,
  'from_this_person_to_poi': 0,
  'loan_advances': 'NaN',
  'long_term_incentive': 180250,
  'other': 427316,
  'poi': False,
  'restricted_stock': 659249,
  'restricted_stock_deferred': 'NaN',
  'salary': 187922,
  'shared_receipt_with_poi': 233,
  'to_messages': 383,
  'total_payments': 618850,
  'total_stock_value': 659249},
 'BHATNAGAR SANJAY': {'bonus': 'NaN',
  'deferral_payments': 'NaN',
  'deferred_income': 'NaN',
  'director_fees': 'NaN',
  'email_address': 'sanjay.bhatnagar@enron.com',
  'exercised_stock_options': 15456290,
  'expenses': 137864,
  'from_messages': 29,
  'from_poi_to_this_person': 0,
  'from_this_person_to_poi': 1,
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 'NaN',
  'poi': False,
  'restricted_stock': 2604490,
  'restricted_stock_deferred': -2604490,
  'salary': 'NaN',
  'shared_receipt_with_poi': 463,
  'to_messages': 523,
  'total_payments': 137864,
  'total_stock_value': 15456290},
 'BIBI PHILIPPE A': {'bonus': 1000000,
  'deferral_payments': 'NaN',
  'deferred_income': 'NaN',
  'director_fees': 'NaN',
  'email_address': 'philippe.bibi@enron.com',
  'exercised_stock_options': 1465734,
  'expenses': 38559,
  'from_messages': 40,
  'from_poi_to_this_person': 23,
  'from_this_person_to_poi': 8,
  'loan_advances': 'NaN',
  'long_term_incentive': 369721,
  'other': 425688,
  'poi': False,
  'restricted_stock': 378082,
  'restricted_stock_deferred': 'NaN',
  'salary': 213625,
  'shared_receipt_with_poi': 1336,
  'to_messages': 1607,
  'total_payments': 2047593,
  'total_stock_value': 1843816},
 'BLACHMAN JEREMY M': {'bonus': 850000,
  'deferral_payments': 'NaN',
  'deferred_income': 'NaN',
  'director_fees': 'NaN',
  'email_address': 'jeremy.blachman@enron.com',
  'exercised_stock_options': 765313,
  'expenses': 84208,
  'from_messages': 14,
  'from_poi_to_this_person': 25,
  'from_this_person_to_poi': 2,
  'loan_advances': 'NaN',
  'long_term_incentive': 831809,
  'other': 272,
  'poi': False,
  'restricted_stock': 189041,
  'restricted_stock_deferred': 'NaN',
  'salary': 248546,
  'shared_receipt_with_poi': 2326,
  'to_messages': 2475,
  'total_payments': 2014835,
  'total_stock_value': 954354},
 'BLAKE JR. NORMAN P': {'bonus': 'NaN',
  'deferral_payments': 'NaN',
  'deferred_income': -113784,
  'director_fees': 113784,
  'email_address': 'NaN',
  'exercised_stock_options': 'NaN',
  'expenses': 1279,
  'from_messages': 'NaN',
  'from_poi_to_this_person': 'NaN',
  'from_this_person_to_poi': 'NaN',
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 'NaN',
  'poi': False,
  'restricted_stock': 'NaN',
  'restricted_stock_deferred': 'NaN',
  'salary': 'NaN',
  'shared_receipt_with_poi': 'NaN',
  'to_messages': 'NaN',
  'total_payments': 1279,
  'total_stock_value': 'NaN'},
 'BOWEN JR RAYMOND M': {'bonus': 1350000,
  'deferral_payments': 'NaN',
  'deferred_income': -833,
  'director_fees': 'NaN',
  'email_address': 'raymond.bowen@enron.com',
  'exercised_stock_options': 'NaN',
  'expenses': 65907,
  'from_messages': 27,
  'from_poi_to_this_person': 140,
  'from_this_person_to_poi': 15,
  'loan_advances': 'NaN',
  'long_term_incentive': 974293,
  'other': 1621,
  'poi': True,
  'restricted_stock': 252055,
  'restricted_stock_deferred': 'NaN',
  'salary': 278601,
  'shared_receipt_with_poi': 1593,
  'to_messages': 1858,
  'total_payments': 2669589,
  'total_stock_value': 252055},
 'BROWN MICHAEL': {'bonus': 'NaN',
  'deferral_payments': 'NaN',
  'deferred_income': 'NaN',
  'director_fees': 'NaN',
  'email_address': 'michael.brown@enron.com',
  'exercised_stock_options': 'NaN',
  'expenses': 49288,
  'from_messages': 41,
  'from_poi_to_this_person': 13,
  'from_this_person_to_poi': 1,
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 'NaN',
  'poi': False,
  'restricted_stock': 'NaN',
  'restricted_stock_deferred': 'NaN',
  'salary': 'NaN',
  'shared_receipt_with_poi': 761,
  'to_messages': 1486,
  'total_payments': 49288,
  'total_stock_value': 'NaN'},
 'BUCHANAN HAROLD G': {'bonus': 500000,
  'deferral_payments': 'NaN',
  'deferred_income': 'NaN',
  'director_fees': 'NaN',
  'email_address': 'john.buchanan@enron.com',
  'exercised_stock_options': 825464,
  'expenses': 600,
  'from_messages': 125,
  'from_poi_to_this_person': 0,
  'from_this_person_to_poi': 0,
  'loan_advances': 'NaN',
  'long_term_incentive': 304805,
  'other': 1215,
  'poi': False,
  'restricted_stock': 189041,
  'restricted_stock_deferred': 'NaN',
  'salary': 248017,
  'shared_receipt_with_poi': 23,
  'to_messages': 1088,
  'total_payments': 1054637,
  'total_stock_value': 1014505},
 'BUTTS ROBERT H': {'bonus': 750000,
  'deferral_payments': 'NaN',
  'deferred_income': -75000,
  'director_fees': 'NaN',
  'email_address': 'bob.butts@enron.com',
  'exercised_stock_options': 'NaN',
  'expenses': 9410,
  'from_messages': 'NaN',
  'from_poi_to_this_person': 'NaN',
  'from_this_person_to_poi': 'NaN',
  'loan_advances': 'NaN',
  'long_term_incentive': 175000,
  'other': 150656,
  'poi': False,
  'restricted_stock': 417619,
  'restricted_stock_deferred': 'NaN',
  'salary': 261516,
  'shared_receipt_with_poi': 'NaN',
  'to_messages': 'NaN',
  'total_payments': 1271582,
  'total_stock_value': 417619},
 'BUY RICHARD B': {'bonus': 900000,
  'deferral_payments': 649584,
  'deferred_income': -694862,
  'director_fees': 'NaN',
  'email_address': 'rick.buy@enron.com',
  'exercised_stock_options': 2542813,
  'expenses': 'NaN',
  'from_messages': 1053,
  'from_poi_to_this_person': 156,
  'from_this_person_to_poi': 71,
  'loan_advances': 'NaN',
  'long_term_incentive': 769862,
  'other': 400572,
  'poi': False,
  'restricted_stock': 901657,
  'restricted_stock_deferred': 'NaN',
  'salary': 330546,
  'shared_receipt_with_poi': 2333,
  'to_messages': 3523,
  'total_payments': 2355702,
  'total_stock_value': 3444470},
 'CALGER CHRISTOPHER F': {'bonus': 1250000,
  'deferral_payments': 'NaN',
  'deferred_income': -262500,
  'director_fees': 'NaN',
  'email_address': 'christopher.calger@enron.com',
  'exercised_stock_options': 'NaN',
  'expenses': 35818,
  'from_messages': 144,
  'from_poi_to_this_person': 199,
  'from_this_person_to_poi': 25,
  'loan_advances': 'NaN',
  'long_term_incentive': 375304,
  'other': 486,
  'poi': True,
  'restricted_stock': 126027,
  'restricted_stock_deferred': 'NaN',
  'salary': 240189,
  'shared_receipt_with_poi': 2188,
  'to_messages': 2598,
  'total_payments': 1639297,
  'total_stock_value': 126027},
 'CARTER REBECCA C': {'bonus': 300000,
  'deferral_payments': 'NaN',
  'deferred_income': -159792,
  'director_fees': 'NaN',
  'email_address': 'rebecca.carter@enron.com',
  'exercised_stock_options': 'NaN',
  'expenses': 'NaN',
  'from_messages': 15,
  'from_poi_to_this_person': 29,
  'from_this_person_to_poi': 7,
  'loan_advances': 'NaN',
  'long_term_incentive': 75000,
  'other': 540,
  'poi': False,
  'restricted_stock': 307301,
  'restricted_stock_deferred': -307301,
  'salary': 261809,
  'shared_receipt_with_poi': 196,
  'to_messages': 312,
  'total_payments': 477557,
  'total_stock_value': 'NaN'},
 'CAUSEY RICHARD A': {'bonus': 1000000,
  'deferral_payments': 'NaN',
  'deferred_income': -235000,
  'director_fees': 'NaN',
  'email_address': 'richard.causey@enron.com',
  'exercised_stock_options': 'NaN',
  'expenses': 30674,
  'from_messages': 49,
  'from_poi_to_this_person': 58,
  'from_this_person_to_poi': 12,
  'loan_advances': 'NaN',
  'long_term_incentive': 350000,
  'other': 307895,
  'poi': True,
  'restricted_stock': 2502063,
  'restricted_stock_deferred': 'NaN',
  'salary': 415189,
  'shared_receipt_with_poi': 1585,
  'to_messages': 1892,
  'total_payments': 1868758,
  'total_stock_value': 2502063},
 'CHAN RONNIE': {'bonus': 'NaN',
  'deferral_payments': 'NaN',
  'deferred_income': -98784,
  'director_fees': 98784,
  'email_address': 'NaN',
  'exercised_stock_options': 'NaN',
  'expenses': 'NaN',
  'from_messages': 'NaN',
  'from_poi_to_this_person': 'NaN',
  'from_this_person_to_poi': 'NaN',
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 'NaN',
  'poi': False,
  'restricted_stock': 32460,
  'restricted_stock_deferred': -32460,
  'salary': 'NaN',
  'shared_receipt_with_poi': 'NaN',
  'to_messages': 'NaN',
  'total_payments': 'NaN',
  'total_stock_value': 'NaN'},
 'CHRISTODOULOU DIOMEDES': {'bonus': 'NaN',
  'deferral_payments': 'NaN',
  'deferred_income': 'NaN',
  'director_fees': 'NaN',
  'email_address': 'diomedes.christodoulou@enron.com',
  'exercised_stock_options': 5127155,
  'expenses': 'NaN',
  'from_messages': 'NaN',
  'from_poi_to_this_person': 'NaN',
  'from_this_person_to_poi': 'NaN',
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 'NaN',
  'poi': False,
  'restricted_stock': 950730,
  'restricted_stock_deferred': 'NaN',
  'salary': 'NaN',
  'shared_receipt_with_poi': 'NaN',
  'to_messages': 'NaN',
  'total_payments': 'NaN',
  'total_stock_value': 6077885},
 'CLINE KENNETH W': {'bonus': 'NaN',
  'deferral_payments': 'NaN',
  'deferred_income': 'NaN',
  'director_fees': 'NaN',
  'email_address': 'NaN',
  'exercised_stock_options': 'NaN',
  'expenses': 'NaN',
  'from_messages': 'NaN',
  'from_poi_to_this_person': 'NaN',
  'from_this_person_to_poi': 'NaN',
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 'NaN',
  'poi': False,
  'restricted_stock': 662086,
  'restricted_stock_deferred': -472568,
  'salary': 'NaN',
  'shared_receipt_with_poi': 'NaN',
  'to_messages': 'NaN',
  'total_payments': 'NaN',
  'total_stock_value': 189518},
 'COLWELL WESLEY': {'bonus': 1200000,
  'deferral_payments': 27610,
  'deferred_income': -144062,
  'director_fees': 'NaN',
  'email_address': 'wes.colwell@enron.com',
  'exercised_stock_options': 'NaN',
  'expenses': 16514,
  'from_messages': 40,
  'from_poi_to_this_person': 240,
  'from_this_person_to_poi': 11,
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 101740,
  'poi': True,
  'restricted_stock': 698242,
  'restricted_stock_deferred': 'NaN',
  'salary': 288542,
  'shared_receipt_with_poi': 1132,
  'to_messages': 1758,
  'total_payments': 1490344,
  'total_stock_value': 698242},
 'CORDES WILLIAM R': {'bonus': 'NaN',
  'deferral_payments': 'NaN',
  'deferred_income': 'NaN',
  'director_fees': 'NaN',
  'email_address': 'bill.cordes@enron.com',
  'exercised_stock_options': 651850,
  'expenses': 'NaN',
  'from_messages': 12,
  'from_poi_to_this_person': 10,
  'from_this_person_to_poi': 0,
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 'NaN',
  'poi': False,
  'restricted_stock': 386335,
  'restricted_stock_deferred': 'NaN',
  'salary': 'NaN',
  'shared_receipt_with_poi': 58,
  'to_messages': 764,
  'total_payments': 'NaN',
  'total_stock_value': 1038185},
 'COX DAVID': {'bonus': 800000,
  'deferral_payments': 'NaN',
  'deferred_income': -41250,
  'director_fees': 'NaN',
  'email_address': 'chip.cox@enron.com',
  'exercised_stock_options': 117551,
  'expenses': 27861,
  'from_messages': 33,
  'from_poi_to_this_person': 0,
  'from_this_person_to_poi': 4,
  'loan_advances': 'NaN',
  'long_term_incentive': 'NaN',
  'other': 494,
  'poi': False,
  'restricted_stock': 378082,
  'restricted_stock_deferred': 'NaN',
  'salary': 314288,
  'shared_receipt_with_poi': 71,
  'to_messages': 102,
  'total_payments': 1101393,
  'total_stock_value': 495633},
 'CUMBERLAND MICHAEL S': {'bonus': 325000,
  'deferral_payments': 'NaN',
  'deferred_income': 'NaN',
  'director_fees': 'NaN',
  'email_address': 'NaN',
  'exercised_stock_options': 'NaN',
  'expenses': 22344,
  'from_messages': 'NaN',
  'from_poi_to_this_person': 'NaN',
  'from_this_person_to_poi': 'NaN',
  'loan_advances': 'NaN',
  'long_term_incentive': 275000,
  'other': 713,
  'poi': False,
  'restricted_stock': 207940,
  'restricted_stock_deferred': 'NaN',
  'salary': 184899,
  'shared_receipt_with_poi': 'NaN',
  'to_messages': 'NaN',
  'total_payments': 807956,
  'total_stock_value': 207940},
 'DEFFNER JOSEPH M': {'bonus': 600000,
  'deferral_payments': 'NaN',
  'deferred_income': 'NaN',
  'director_fees': 'NaN',
  'email_address': 'joseph.deffner@enron.com',
  'exercised_stock_options': 17378,
  'expenses': 41626,
  'from_messages': 74,
  'from_poi_to_this_person': 115,
  'from_this_person_to_poi': 4,
  'loan_advances': 'NaN',
  'long_term_incentive': 335349,
  'other': 25553,
  'poi': False,
  'restricted_stock': 141833,
  'restricted_stock_deferred': 'NaN',
  'salary': 206121,
  'shared_receipt_with_poi': 552,
  'to_messages': 714,
  'total_payments': 1208649,
  'total_stock_value': 159211},
 'DELAINEY DAVID W': {'bonus': 3000000,
  'deferral_payments': 'NaN',
  'deferred_income': 'NaN',
  'director_fees': 'NaN',
  'email_address': 'david.delainey@enron.com',
  'exercised_stock_options': 2291113,
  'expenses': 86174,
  'from_messages': 3069,
  'from_poi_to_this_person': 66,
  'from_this_person_to_poi': 609,
  'loan_advances': 'NaN',
  'long_term_incentive': 1294981,
  'other': 1661,
  'poi': True,
  'restricted_stock': 1323148,
  'restricted_stock_deferred': 'NaN',
  'salary': 365163,
  'shared_receipt_with_poi': 2097,
  'to_messages': 3093,
  'total_payments': 4747979,
  'total_stock_value': 3614261},
 'DERRICK JR. JAMES V': {'bonus': 800000,
  'deferral_payments': 'NaN',
  'deferred_income': -1284000,
  'director_fees': 'NaN',
  'email_address': 'james.derrick@enron.com',
  'exercised_stock_options': 8831913,
  'expenses': 51124,
  'from_messages': 909,
  'from_poi_to_this_person': 64,
  'from_this_person_to_poi': 20,
  'loan_advances': 'NaN',

In [22]:
# update the dataframe

# Formatting for the output:
pd.set_option('display.float_format', lambda x: '%.3f' % x)

# Convert dictionary to DataFrame
enron_df = pd.DataFrame.from_dict(data_dict, orient = 'index', dtype = float)

# reorganize columns
enron_df = enron_df[
['salary',
'bonus',
'long_term_incentive',
'deferred_income',
'deferral_payments',
'loan_advances',
'other',
'expenses',
'director_fees',
'total_payments',
 'exercised_stock_options',
'restricted_stock',
 'restricted_stock_deferred',
 'total_stock_value',
 'email_address',
 'to_messages',
 'shared_receipt_with_poi',
 'from_messages',
 'from_this_person_to_poi',
 'poi',
 'from_poi_to_this_person']]

# Change the NaN to 0

enron_df = enron_df.fillna(0)
enron_df.head()

,salary,bonus,long_term_incentive,deferred_income,deferral_payments,loan_advances,other,expenses,director_fees,total_payments,exercised_stock_options,restricted_stock,restricted_stock_deferred,total_stock_value,email_address,to_messages,shared_receipt_with_poi,from_messages,from_this_person_to_poi,poi,from_poi_to_this_person
ALLEN PHILLIP K,201955.000,4175000.000,304805.000,-3081055.000,2869717.000,0.000,152.000,13868.000,0.000,4484442.000,1729541.000,126027.000,-126027.000,1729541.000,phillip.allen@enron.com,2902.000,1407.000,2195.000,65.000,0.000,47.000
BADUM JAMES P,0.000,0.000,0.000,0.000,178980.000,0.000,0.000,3486.000,0.000,182466.000,257817.000,0.000,0.000,257817.000,NaN,0.000,0.000,0.000,0.000,0.000,0.000
BANNANTINE JAMES M,477.000,0.000,0.000,-5104.000,0.000,0.000,864523.000,56301.000,0.000,916197.000,4046157.000,1757552.000,-560222.000,5243487.000,james.bannantine@enron.com,566.000,465.000,29.000,0.000,0.000,39.000
BAXTER JOHN C,267102.000,1200000.000,1586055.000,-1386055.000,1295738.000,0.000,2660303.000,11200.000,0.000,5634343.000,6680544.000,3942714.000,0.000,10623258.000,NaN,0.000,0.000,0.000,0.000,0.000,0.000
BAY FRANKLIN R,239671.000,400000.000,0.000,-201641.000,260455.000,0.000,69.000,129142.000,0.000,827696.000,0.000,145796.000,-82782.000,63014.000,frank.bay@enron.com,0.000,0.000,0.000,0.000,0.000,0.000

In [23]:
# double check for column shift
enron_df['add_total_payments'] = \
enron_df['salary'] + \
enron_df['bonus'] + \
enron_df['long_term_incentive'] + \
enron_df['deferred_income'] + \
enron_df['deferral_payments'] + \
enron_df['loan_advances'] + \
enron_df['other'] +  \
enron_df['expenses'] + \
enron_df['director_fees'] 

enron_df['add_total_stock'] = \
enron_df['exercised_stock_options'] + \
enron_df['restricted_stock'] + \
enron_df['restricted_stock_deferred'] 


enron_df['check_total_payments'] = enron_df['add_total_payments'] == enron_df['total_payments']
enron_df['check_total_stock'] = enron_df['add_total_stock'] == enron_df['total_stock_value']

In [24]:
enron_df[enron_df['check_total_payments']==0]

Empty DataFrame
Columns: [salary, bonus, long_term_incentive, deferred_income, deferral_payments, loan_advances, other, expenses, director_fees, total_payments, exercised_stock_options, restricted_stock, restricted_stock_deferred, total_stock_value, email_address, to_messages, shared_receipt_with_poi, from_messages, from_this_person_to_poi, poi, from_poi_to_this_person, add_total_payments, add_total_stock, check_total_payments, check_total_stock]
Index: []

In [25]:
enron_df[enron_df['check_total_stock']==0]

Empty DataFrame
Columns: [salary, bonus, long_term_incentive, deferred_income, deferral_payments, loan_advances, other, expenses, director_fees, total_payments, exercised_stock_options, restricted_stock, restricted_stock_deferred, total_stock_value, email_address, to_messages, shared_receipt_with_poi, from_messages, from_this_person_to_poi, poi, from_poi_to_this_person, add_total_payments, add_total_stock, check_total_payments, check_total_stock]
Index: []

In [26]:
# recheck df stats
enron_df.describe()

,salary,bonus,long_term_incentive,deferred_income,deferral_payments,loan_advances,other,expenses,director_fees,total_payments,exercised_stock_options,restricted_stock,restricted_stock_deferred,total_stock_value,to_messages,shared_receipt_with_poi,from_messages,from_this_person_to_poi,poi,from_poi_to_this_person,add_total_payments,add_total_stock
count,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000,143.000
mean,186742.860,680724.608,339314.182,-195754.483,224359.413,586888.112,295842.608,36609.776,9779.839,2164506.916,2180167.832,911344.748,-52984.531,3038528.049,1247.217,707.524,366.126,24.797,0.126,39.028,2164506.916,3038528.049
std,197117.072,1236179.688,689013.933,607751.295,756258.114,6818177.362,1135225.135,46050.414,30518.512,8808363.755,4937260.144,2005940.550,274107.890,6288440.349,2243.006,1079.457,1455.452,80.032,0.333,74.466,8808363.755,6288440.349
min,0.000,0.000,0.000,-3504386.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,-2604490.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,0.000,0.000,0.000,-39798.000,0.000,0.000,0.000,0.000,0.000,89292.500,0.000,45698.500,0.000,288212.000,0.000,0.000,0.000,0.000,0.000,0.000,89292.500,288212.000
50%,210692.000,300000.000,0.000,0.000,0.000,0.000,891.000,22344.000,0.000,916197.000,608750.000,363428.000,0.000,985032.000,383.000,114.000,18.000,0.000,0.000,4.000,916197.000,985032.000
75%,270259.000,800000.000,374825.500,0.000,9110.000,0.000,149204.000,54522.000,0.000,1901558.500,1698900.500,861142.000,0.000,2413007.500,1639.000,967.500,54.000,14.000,0.000,41.500,1901558.500,2413007.500
max,1111258.000,8000000.000,5145434.000,0.000,6426990.000,81525000.000,10359729.000,228763.000,125034.000,103559793.000,34348384.000,14761694.000,0.000,49110078.000,15149.000,5521.000,14368.000,609.000,1.000,528.000,103559793.000,49110078.000

In [27]:
# let's look for any correlations in the data
enron_df.corr(method ='pearson')

,salary,bonus,long_term_incentive,deferred_income,deferral_payments,loan_advances,other,expenses,director_fees,total_payments,exercised_stock_options,restricted_stock,restricted_stock_deferred,total_stock_value,to_messages,shared_receipt_with_poi,from_messages,from_this_person_to_poi,poi,from_poi_to_this_person,add_total_payments,add_total_stock,check_total_payments,check_total_stock
salary,1.000,0.649,0.559,-0.328,0.242,0.388,0.546,0.332,-0.306,0.527,0.420,0.525,0.017,0.498,0.395,0.510,0.143,0.206,0.339,0.406,0.527,0.498,nan,nan
bonus,0.649,1.000,0.497,-0.330,0.173,0.433,0.384,0.228,-0.178,0.571,0.395,0.416,0.050,0.445,0.519,0.664,0.174,0.448,0.358,0.640,0.571,0.445,nan,nan
long_term_incentive,0.559,0.497,1.000,-0.295,0.119,0.402,0.535,0.083,-0.159,0.530,0.379,0.336,0.044,0.407,0.191,0.278,0.055,0.156,0.256,0.266,0.530,0.407,nan,nan
deferred_income,-0.328,-0.330,-0.295,1.000,-0.543,-0.025,-0.265,-0.032,0.072,-0.108,-0.255,-0.120,0.079,-0.235,-0.120,-0.235,-0.014,-0.004,-0.274,-0.194,-0.108,-0.235,nan,nan
deferral_payments,0.242,0.173,0.119,-0.543,1.000,0.014,0.369,-0.029,-0.096,0.146,0.108,0.083,-0.007,0.111,0.123,0.209,0.028,0.001,-0.040,0.216,0.146,0.111,nan,nan
loan_advances,0.388,0.433,0.402,-0.025,0.014,1.000,0.759,0.118,-0.028,0.973,0.552,0.585,0.017,0.621,0.115,0.137,-0.020,-0.010,0.220,0.100,0.973,0.621,nan,nan
other,0.546,0.384,0.535,-0.265,0.369,0.759,1.000,0.131,-0.084,0.838,0.531,0.637,0.038,0.622,0.106,0.180,-0.055,-0.050,0.170,0.160,0.838,0.622,nan,nan
expenses,0.332,0.228,0.083,-0.032,-0.029,0.118,0.131,1.000,-0.140,0.154,0.158,0.182,-0.155,0.175,0.231,0.276,0.148,0.125,0.192,0.132,0.154,0.175,nan,nan
director_fees,-0.306,-0.178,-0.159,0.072,-0.096,-0.028,-0.084,-0.140,1.000,-0.077,-0.136,-0.145,0.052,-0.151,-0.178,-0.211,-0.081,-0.100,-0.122,-0.169,-0.077,-0.151,nan,nan
total_payments,0.527,0.571,0.530,-0.108,0.146,0.973,0.838,0.154,-0.077,1.000,0.582,0.630,0.033,0.660,0.202,0.258,0.012,0.066,0.249,0.223,1.000,0.660,nan,nan
exercised_stock_options,0.420,0.395,0.379,-0.255,0.108,0.552,0.531,0.158,-0.136,0.582,1.000,0.594,-0.229,0.965,0.076,0.117,-0.028,-0.004,0.370,0.112,0.582,0.965,nan,nan
restricted_stock,0.525,0.416,0.336,-0.120,0.083,0.585,0.637,0.182,-0.145,0.630,0.594,1.000,-0.065,0.782,0.154,0.177,0.018,0.054,0.243,0.116,0.630,0.782,nan,nan
restricted_stock_deferred,0.017,0.050,0.044,0.079,-0.007,0.017,0.038,-0.155,0.052,0.033,-0.229,-0.065,1.000,-0.157,0.018,0.006,0.001,0.032,0.074,0.021,0.033,-0.157,nan,nan
total_stock_value,0.498,0.445,0.407,-0.235,0.111,0.621,0.622,0.175,-0.151,0.660,0.965,0.782,-0.157,1.000,0.110,0.149,-0.016,0.016,0.371,0.126,0.660,1.000,nan,nan
to_messages,0.395,0.519,0.191,-0.120,0.123,0.115,0.106,0.231,-0.178,0.202,0.076,0.154,0.018,0.110,1.000,0.881,0.508,0.605,0.107,0.618,0.202,0.110,nan,nan
shared_receipt_with_poi,0.510,0.664,0.278,-0.235,0.209,0.137,0.180,0.276,-0.211,0.258,0.117,0.177,0.006,0.149,0.881,1.000,0.301,0.524,0.240,0.732,0.258,0.149,nan,nan
from_messages,0.143,0.174,0.055,-0.014,0.028,-0.020,-0.055,0.148,-0.081,0.012,-0.028,0.018,0.001,-0.016,0.508,0.301,1.000,0.609,-0.035,0.253,0.012,-0.016,nan,nan
from_this_person_to_poi,0.206,0.448,0.156,-0.004,0.001,-0.010,-0.050,0.125,-0.100,0.066,-0.004,0.054,0.032,0.016,0.605,0.524,0.609,1.000,0.129,0.497,0.066,0.016,nan,nan
poi,0.339,0.358,0.256,-0.274,-0.040,0.220,0.170,0.192,-0.122,0.249,0.370,0.243,0.074,0.371,0.107,0.240,-0.035,0.129,1.000,0.189,0.249,0.371,nan,nan
from_poi_to_this_person,0.406,0.640,0.266,-0.194,0.216,0.100,0.160,0.132,-0.169,0.223,0.112,0.116,0.021,0.126,0.618,0.732,0.253,0.497,0.189,1.000,0.223,0.126,nan,nan
add_total_payments,0.527,0.571,0.530,-0.108,0.146,0.973,0.838,0.154,-0.077,1.000,0.582,0.630,0.033,0.660,0.202,0.258,0.012,0.066,0.249,0.223,1.000,0.660,nan,nan
add_total_stock,0.498,0.445,0.407,-0.235,0.111,0.621,0.622,0.175,-0.151,0.660,0.965,0.782,-0.157,1.000,0.110,0.149,-0.016,0.016,0.371,0.126,0.660,1.000,nan,nan
check_total_payments,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
check_total_stock,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [28]:
# lets see how many people are outliers

outlier_POIs = dict()

cases = 0
for column_name in list(enron_df):
    if enron_df[column_name].dtype == 'float' and column_name != 'poi':
        cases +=1
        test_data = enron_df[enron_df[column_name]!=0]
        Q1 = test_data[column_name].quantile(0.25)
        Q3 = test_data[column_name].quantile(0.75)
        IQR = Q3 - Q1

        # Filtering Values between Q1-1.5IQR and Q3+1.5IQR
        query_str = '(@Q1 - 2 * @IQR) >= ' + column_name + ' or  (@Q3 + 2 * @IQR) <=' + column_name
        filtered = test_data.query(query_str)

        print column_name + ": " + str(len(filtered))
        filtered = filtered.sort_values(column_name)
        print filtered[column_name].head(10)
        print ""
        
        for person in filtered.index.tolist():
            try:
               outlier_POIs[person] = 1 + outlier_POIs[person]
            except:
               outlier_POIs[person] = 1 

print "Total Cases:" + str(cases)

salary: 7
BANNANTINE JAMES M       477.000
GRAY RODNEY             6615.000
WHALLEY LAWRENCE G    510364.000
PICKERING MARK R      655037.000
FREVERT MARK A       1060932.000
LAY KENNETH L        1072321.000
SKILLING JEFFREY K   1111258.000
Name: salary, dtype: float64

bonus: 8
DELAINEY DAVID W     3000000.000
WHALLEY LAWRENCE G   3000000.000
KITCHEN LOUISE       3100000.000
ALLEN PHILLIP K      4175000.000
BELDEN TIMOTHY N     5249999.000
SKILLING JEFFREY K   5600000.000
LAY KENNETH L        7000000.000
LAVORATO JOHN J      8000000.000
Name: bonus, dtype: float64

long_term_incentive: 4
LAVORATO JOHN J   2035380.000
ECHOLS JOHN B     2234774.000
LAY KENNETH L     3600000.000
MARTIN AMANDA K   5145434.000
Name: long_term_incentive, dtype: float64

deferred_income: 5
RICE KENNETH D     -3504386.000
FREVERT MARK A     -3367011.000
HANNON KEVIN P     -3117011.000
ALLEN PHILLIP K    -3081055.000
BELDEN TIMOTHY N   -2334434.000
Name: deferred_income, dtype: float64

deferral_payments: 4
ALLEN PHILLIP K    2869717.000
HUMPHREY GENE E    2964506.000
HORTON STANLEY C   3131860.000
FREVERT MARK A     6426990.000
Name: deferral_payments, dtype: float64

loan_advances: 0
Series([], Name: loan_advances, dtype: float64)

other: 9
WHITE JR THOMAS E    1085463.000
IZZO LAWRENCE L      1553729.000
SHELBY REX           1573324.000
PAI LOU L            1829457.000
SHERRIFF JOHN R      1852186.000
BAXTER JOHN C        2660303.000
MARTIN AMANDA K      2818454.000
FREVERT MARK A       7427621.000
LAY KENNETH L       10359729.000
Name: other, dtype: float64

expenses: 2
URQUHART JOHN A    228656.000
MCCLELLAN GEORGE   228763.000
Name: expenses, dtype: float64

director_fees: 3
POWERS WILLIAM    17500.000
URQUHART JOHN A   36666.000
MEYER JEROME J    38346.000
Name: director_fees, dtype: float64

total_payments: 7
BELDEN TIMOTHY N       5501630.000
BAXTER JOHN C          5634343.000
MARTIN AMANDA K        8407016.000
SKILLING JEFFREY K     8682716.000
LAVORATO JOHN J       10425757.000
FREVERT MARK A        17252530.000
LAY KENNETH L        103559793.000
Name: total_payments, dtype: float64

exercised_stock_options: 12
BAXTER JOHN C          6680544.000
REDMOND BRIAN L        7509039.000
DIMICHELE RICHARD G    8191755.000
YEAGER F SCOTT         8308552.000
DERRICK JR. JAMES V    8831913.000
FREVERT MARK A        10433518.000
PAI LOU L             15364167.000
BHATNAGAR SANJAY      15456290.000
SKILLING JEFFREY K    19250000.000
RICE KENNETH D        19794175.000
Name: exercised_stock_options, dtype: float64

restricted_stock: 13
CAUSEY RICHARD A     2502063.000
BHATNAGAR SANJAY     2604490.000
RICE KENNETH D       2748364.000
WHALLEY LAWRENCE G   2796177.000
YEAGER F SCOTT       3576206.000
IZZO LAWRENCE L      3654808.000
BAXTER JOHN C        3942714.000
KEAN STEVEN J        4131594.000
FREVERT MARK A       4188667.000
SKILLING JEFFREY K   6843672.000
Name: restricted_stock, dtype: float64

restricted_stock_deferred: 2
BHATNAGAR SANJAY      -2604490.000
DERRICK JR. JAMES V   -1787380.000
Name: restricted_stock_deferred, dtype: float64

total_stock_value: 12
DIMICHELE RICHARD G    8317782.000
DERRICK JR. JAMES V    8831913.000
BAXTER JOHN C         10623258.000
YEAGER F SCOTT        11884758.000
FREVERT MARK A        14622185.000
WHITE JR THOMAS E     15144123.000
BHATNAGAR SANJAY      15456290.000
RICE KENNETH D        22542539.000
PAI LOU L             23817930.000
SKILLING JEFFREY K    26093672.000
Name: total_stock_value, dtype: float64

to_messages: 6
LAVORATO JOHN J      7259.000
BECK SALLY W         7315.000
BELDEN TIMOTHY N     7991.000
KITCHEN LOUISE       8305.000
KEAN STEVEN J       12754.000
SHAPIRO RICHARD S   15149.000
Name: to_messages, dtype: float64

shared_receipt_with_poi: 1
BELDEN TIMOTHY N   5521.000
Name: shared_receipt_with_poi, dtype: float64

from_messages: 17
BELDEN TIMOTHY N       484.000
WHALLEY LAWRENCE G     556.000
DERRICK JR. JAMES V    909.000
BUY RICHARD B         1053.000
HAYSLETT RODERICK J   1061.000
HORTON STANLEY C      1073.000
SHAPIRO RICHARD S     1215.000
KITCHEN LOUISE        1728.000
HAEDICKE MARK E       1941.000
ALLEN PHILLIP K       2195.000
Name: from_messages, dtype: float64

from_this_person_to_poi: 8
BELDEN TIMOTHY N      108.000
KAMINSKI WINCENTY J   171.000
KITCHEN LOUISE        194.000
MCCONNELL MICHAEL S   194.000
BECK SALLY W          386.000
KEAN STEVEN J         387.000
LAVORATO JOHN J       411.000
DELAINEY DAVID W      609.000
Name: from_this_person_to_poi, dtype: float64

from_poi_to_this_person: 5
COLWELL WESLEY     240.000
FREVERT MARK A     242.000
KITCHEN LOUISE     251.000
DIETRICH JANET R   305.000
LAVORATO JOHN J    528.000
Name: from_poi_to_this_person, dtype: float64

add_total_payments: 7
BELDEN TIMOTHY N       5501630.000
BAXTER JOHN C          5634343.000
MARTIN AMANDA K        8407016.000
SKILLING JEFFREY K     8682716.000
LAVORATO JOHN J       10425757.000
FREVERT MARK A        17252530.000
LAY KENNETH L        103559793.000
Name: add_total_payments, dtype: float64

add_total_stock: 12
DIMICHELE RICHARD G    8317782.000
DERRICK JR. JAMES V    8831913.000
BAXTER JOHN C         10623258.000
YEAGER F SCOTT        11884758.000
FREVERT MARK A        14622185.000
WHITE JR THOMAS E     15144123.000
BHATNAGAR SANJAY      15456290.000
RICE KENNETH D        22542539.000
PAI LOU L             23817930.000
SKILLING JEFFREY K    26093672.000
Name: add_total_stock, dtype: float64

Total Cases:21

In [29]:
# lets count'em up

outlier_POIs_df = pd.DataFrame.from_dict(outlier_POIs, orient = 'index', dtype = int)
outlier_POIs_df.columns = ['Count']
outlier_POIs_df = outlier_POIs_df.sort_values('Count', ascending = False)
outlier_POIs_df.head(10)

                     Count
FREVERT MARK A          11
LAY KENNETH L           10
BELDEN TIMOTHY N         8
SKILLING JEFFREY K       8
LAVORATO JOHN J          8
BAXTER JOHN C            7
DERRICK JR. JAMES V      5
KITCHEN LOUISE           5
PAI LOU L                5
BHATNAGAR SANJAY         5

LAY KENNETH L and SKILLING JEFFREY K are near the top of the list the was expected. Other names there are: FREVERT MARK A, BELDEN TIMOTHY N, LAVORATO JOHN J.

FREVERT MARK A is a strong outlier since he shows up in 11 times. These seem like real outliers and they will be kept.

**There are many features with NaN values.  Let's look at the proportions of NaN values for each feature.**

In [30]:
# What is the rate of NaN values for each column
for col in enron_df.columns:
    if str(enron_df[col].dtype) != 'bool':
        print col,(enron_df[enron_df[col] != 0][col].count()) \
        ,round((enron_df[enron_df[col] != 0][col].count())/ \
        (float(enron_df.shape[0])),2)

salary 94 0.66
bonus 81 0.57
long_term_incentive 65 0.45
deferred_income 49 0.34
deferral_payments 37 0.26
loan_advances 3 0.02
other 90 0.63
expenses 96 0.67
director_fees 15 0.1
total_payments 123 0.86
exercised_stock_options 100 0.7
restricted_stock 110 0.77
restricted_stock_deferred 17 0.12
total_stock_value 125 0.87
email_address 143 1.0
to_messages 86 0.6
shared_receipt_with_poi 86 0.6
from_messages 86 0.6
from_this_person_to_poi 66 0.46
poi 18 0.13
from_poi_to_this_person 74 0.52
add_total_payments 123 0.86
add_total_stock 125 0.87

In [31]:
# creating the first feature list from non-NaN data ratios of > 50%

POI = 18
non_POI = 125

first_feature_list = ['poi']
all_features_list = ['poi']

for feature in data_dict[data_dict.keys()[0]].keys():
    nan_poi = 0
    nan_non_poi = 0
    valid_data = 0 
    print "\n"+feature
    for person in data_dict.keys():
        if data_dict[person][feature] =='NaN':
            if data_dict[person]['poi']:
                nan_poi +=1
            else:
                nan_non_poi +=1
        else:
            valid_data +=1
    print "NaN in POIs: " + str(nan_poi) + " (" + str(round(float(nan_poi)/float(POI)*100,2))+"%)"
    print "NaN in non-POIs: " + str(nan_non_poi) + " (" + str(round(float(nan_non_poi)/float(non_POI)*100,2))+"%)"
    print "Valid: " + str(valid_data)  +" (" + str(round(float(valid_data)/float(POI+non_POI)*100,2))+"%)"
 
    
   # Keep feature only if at least 50% is valid:
    if round(float(valid_data)/float(POI+non_POI)*100,2)>50:
        # ignore email_address, since it is just text, and poi, which must be first
        if feature !="email_address" and feature !="poi":
            first_feature_list.append(feature)
            
    # save all features to allow for comparison:
    # ignore email_address, since it is just text, and poi, which must be first
    if feature !="email_address" and feature !="poi":
        all_features_list.append(feature)

salary
NaN in POIs: 1 (5.56%)
NaN in non-POIs: 48 (38.4%)
Valid: 94 (65.73%)

to_messages
NaN in POIs: 4 (22.22%)
NaN in non-POIs: 53 (42.4%)
Valid: 86 (60.14%)

deferral_payments
NaN in POIs: 13 (72.22%)
NaN in non-POIs: 93 (74.4%)
Valid: 37 (25.87%)

total_payments
NaN in POIs: 0 (0.0%)
NaN in non-POIs: 20 (16.0%)
Valid: 123 (86.01%)

exercised_stock_options
NaN in POIs: 6 (33.33%)
NaN in non-POIs: 37 (29.6%)
Valid: 100 (69.93%)

bonus
NaN in POIs: 2 (11.11%)
NaN in non-POIs: 60 (48.0%)
Valid: 81 (56.64%)

restricted_stock
NaN in POIs: 1 (5.56%)
NaN in non-POIs: 32 (25.6%)
Valid: 110 (76.92%)

shared_receipt_with_poi
NaN in POIs: 4 (22.22%)
NaN in non-POIs: 53 (42.4%)
Valid: 86 (60.14%)

restricted_stock_deferred
NaN in POIs: 18 (100.0%)
NaN in non-POIs: 108 (86.4%)
Valid: 17 (11.89%)

total_stock_value
NaN in POIs: 0 (0.0%)
NaN in non-POIs: 18 (14.4%)
Valid: 125 (87.41%)

expenses
NaN in POIs: 0 (0.0%)
NaN in non-POIs: 47 (37.6%)
Valid: 96 (67.13%)

loan_advances
NaN in POIs: 17 (94.44%)
NaN in non-POIs: 123 (98.4%)
Valid: 3 (2.1%)

from_messages
NaN in POIs: 4 (22.22%)
NaN in non-POIs: 53 (42.4%)
Valid: 86 (60.14%)

other
NaN in POIs: 0 (0.0%)
NaN in non-POIs: 53 (42.4%)
Valid: 90 (62.94%)

from_this_person_to_poi
NaN in POIs: 4 (22.22%)
NaN in non-POIs: 53 (42.4%)
Valid: 86 (60.14%)

poi
NaN in POIs: 0 (0.0%)
NaN in non-POIs: 0 (0.0%)
Valid: 143 (100.0%)

director_fees
NaN in POIs: 18 (100.0%)
NaN in non-POIs: 110 (88.0%)
Valid: 15 (10.49%)

deferred_income
NaN in POIs: 7 (38.89%)
NaN in non-POIs: 87 (69.6%)
Valid: 49 (34.27%)

long_term_incentive
NaN in POIs: 6 (33.33%)
NaN in non-POIs: 72 (57.6%)
Valid: 65 (45.45%)

email_address
NaN in POIs: 0 (0.0%)
NaN in non-POIs: 32 (25.6%)
Valid: 111 (77.62%)

from_poi_to_this_person
NaN in POIs: 4 (22.22%)
NaN in non-POIs: 53 (42.4%)
Valid: 86 (60.14%)

Let's create 5 new features:

* nf_bonus:  the raio of bonus to total payments

* nf_salary: the raio of salary to total payments

* nf_excised_stock: the raio of excised stockbonus to total payments

* nf_poi_to: the ratio of emails a person received from a poi

* nf_to_poi: the ratio of emails a person sent to a poi

Feature Reasoning:  These features had high correlations with total payments.  I suspect a POI will have high ratios in these new features for conducting fraudulent activity.  These new features will quantify this and will hopefully increase the predictive power of the algorithm.

In [32]:
import support_functions


# nf_bonus
data_dict = support_functions.create_feature(data_dict,
                                      "bonus",
                                      "total_payments",
                                      "nf_bonus")

# nf_salary
data_dict = support_functions.create_feature(data_dict,
                                      "salary",
                                      "total_payments",
                                      "nf_salary")


# nf_exercised_stock
data_dict = support_functions.create_feature(data_dict,
                                      "exercised_stock_options",
                                      "total_payments",
                                      "nf_exercised_stock")


# nf_to_poi
data_dict = support_functions.create_feature(data_dict,
                                      "from_this_person_to_poi",
                                      "from_messages",
                                      "nf_to_poi")

# nf_poi_to
data_dict = support_functions.create_feature(data_dict,
                                      "from_poi_to_this_person",
                                      "to_messages",
                                      "nf_poi_to")




# Add the  new features
first_feature_list = first_feature_list + ['nf_bonus',
                                 'nf_salary', 'nf_exercised_stock', 'nf_to_poi', 'nf_poi_to']
  
all_features_list = all_features_list + ['nf_bonus',
                                 'nf_salary', 'nf_exercised_stock', 'nf_to_poi', 'nf_poi_to']

In [33]:
# setup 3 algo tests
from tester import test_classifier

from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier


# Naive Bayes
clf_NB = GaussianNB()

# Decision Tree
clf_TREE = DecisionTreeClassifier()

# AdaBoost:
clf_ADA = AdaBoostClassifier()

C:\Users\trobe\Anaconda3\envs\UDACITY_DAND\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\Users\trobe\Anaconda3\envs\UDACITY_DAND\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [34]:
# Print the feature list
print  first_feature_list
print "\n Numbers of features: " + str(len(first_feature_list))

['poi', 'salary', 'to_messages', 'total_payments', 'exercised_stock_options', 'bonus', 'restricted_stock', 'shared_receipt_with_poi', 'total_stock_value', 'expenses', 'from_messages', 'other', 'from_this_person_to_poi', 'from_poi_to_this_person', 'nf_bonus', 'nf_salary', 'nf_exercised_stock', 'nf_to_poi', 'nf_poi_to']

 Numbers of features: 19

In [35]:
# import feature formatter
from feature_format import featureFormat, targetFeatureSplit
from sklearn.model_selection import train_test_split

import sys
sys.path.append("./tools/")

In [36]:
# format the feature list
data = featureFormat(data_dict, all_features_list, sort_keys = True)
labels, features = targetFeatureSplit(data)

features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=42)

**Let's see what the best features are from the first set**

In [37]:
# Print importance of each feature

clf_ADA.fit(features_train,labels_train)
for feature, imp in zip(first_feature_list[1:],clf_ADA.feature_importances_):
    print feature +": " + str(round(imp,2))

salary: 0.08
to_messages: 0.0
total_payments: 0.02
exercised_stock_options: 0.08
bonus: 0.02
restricted_stock: 0.06
shared_receipt_with_poi: 0.08
total_stock_value: 0.1
expenses: 0.0
from_messages: 0.0
other: 0.06
from_this_person_to_poi: 0.0
from_poi_to_this_person: 0.04
nf_bonus: 0.2
nf_salary: 0.0
nf_exercised_stock: 0.0
nf_to_poi: 0.0
nf_poi_to: 0.02

In [38]:
# Remove some features 

first_feature_list.remove('salary')
first_feature_list.remove('to_messages')
first_feature_list.remove('from_messages')
first_feature_list.remove('from_this_person_to_poi')
first_feature_list.remove('from_poi_to_this_person')

In [39]:
# Print the feature list
#first_feature_list = feature_list_one
print  first_feature_list
print "\n Numbers of features: " + str(len(first_feature_list))

['poi', 'total_payments', 'exercised_stock_options', 'bonus', 'restricted_stock', 'shared_receipt_with_poi', 'total_stock_value', 'expenses', 'other', 'nf_bonus', 'nf_salary', 'nf_exercised_stock', 'nf_to_poi', 'nf_poi_to']

 Numbers of features: 14

redo feature format

In [40]:
# format the feature list
data = featureFormat(data_dict, all_features_list, sort_keys = True)
labels, features = targetFeatureSplit(data)


features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=42)

**Let's pick an algo**

In [41]:
# let's test 3 algos and choose one
test_classifier(clf_NB, data_dict, first_feature_list)
test_classifier(clf_TREE, data_dict, first_feature_list)
test_classifier(clf_ADA, data_dict, first_feature_list)

GaussianNB(priors=None)
	Accuracy: 0.84573	Precision: 0.37173	Recall: 0.22750	F1: 0.28226	F2: 0.24664
	Total predictions: 15000	True positives:  455	False positives:  769	False negatives: 1545	True negatives: 12231

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
	Accuracy: 0.81847	Precision: 0.31678	Recall: 0.31250	F1: 0.31462	F2: 0.31335
	Total predictions: 15000	True positives:  625	False positives: 1348	False negatives: 1375	True negatives: 11652

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)
	Accuracy: 0.84087	Precision: 0.38078	Recall: 0.30900	F1: 0.34115	F2: 0.32111
	Total predictions: 15000	True positives:  618	False positives: 1005	False negatives: 1382	True negatives: 11995

**going to choose AdaBoost since it has the highest precision**

**Let's see what the best features are from the first set**

In [42]:
# Print importance of each feature

clf_ADA.fit(features_train,labels_train)
for feature, imp in zip(first_feature_list[1:],clf_ADA.feature_importances_):
    print feature +": " + str(round(imp,2))

total_payments: 0.08
exercised_stock_options: 0.0
bonus: 0.02
restricted_stock: 0.08
shared_receipt_with_poi: 0.02
total_stock_value: 0.06
expenses: 0.08
other: 0.1
nf_bonus: 0.0
nf_salary: 0.0
nf_exercised_stock: 0.06
nf_to_poi: 0.0
nf_poi_to: 0.04

**Let's try GridSearch**

to get starting values for estimator and learning_rate for later fine tuning

In [43]:
from sklearn.model_selection import GridSearchCV

In [44]:
# Gridsearch for learning rate and estimator hyperparameters
from sklearn.model_selection import GridSearchCV
parameters = {'learning_rate':[0.1, 0.2, 0.3, 0.5, 0.7,0.8, 0.9, 1, 2,3, 5, 10],
              'n_estimators':[1,5,8,10,11, 12, 13, 14, 15, 16, 17, 18,50,100,1000, 2000] }
clf_ADA = AdaBoostClassifier()
clf = GridSearchCV(clf_ADA, parameters, scoring = 'f1', cv = 10 )
clf.fit(features, labels)

print clf.best_params_
print clf.best_score_

C:\Users\trobe\Anaconda3\envs\UDACITY_DAND\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)

{'n_estimators': 13, 'learning_rate': 0.9}
0.49941724941724935

# Classifier Tuning - First Feature List

In [45]:
lr = clf.best_params_['learning_rate']
n_est = clf.best_params_['n_estimators']
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, first_feature_list)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=0.9, n_estimators=13, random_state=None)
	Accuracy: 0.85180	Precision: 0.42098	Recall: 0.29700	F1: 0.34828	F2: 0.31559
	Total predictions: 15000	True positives:  594	False positives:  817	False negatives: 1406	True negatives: 12183

**trying some other hyperparameters**

In [46]:
lr = 0.9
n_est = 14
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, first_feature_list)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=0.9, n_estimators=14, random_state=None)
	Accuracy: 0.85220	Precision: 0.42365	Recall: 0.30100	F1: 0.35194	F2: 0.31950
	Total predictions: 15000	True positives:  602	False positives:  819	False negatives: 1398	True negatives: 12181

got it (precision > .30  and recall > .30) but not good enough.  Let's keep going

# Classifier Tuning - Second Feature List

In [47]:
# creating a new list from the important features
feature_list_two = ['poi']
for feature, imp in zip(first_feature_list[1:],clf_ADA.feature_importances_):
    if imp > 0.00:
        feature_list_two.append(feature)

In [48]:
# Take the best importance from the first list
second_feature_list = feature_list_two

# print the feature list
print  second_feature_list
print "\n Numbers of features: " + str(len(second_feature_list))

['poi', 'exercised_stock_options', 'restricted_stock', 'shared_receipt_with_poi', 'expenses', 'other', 'nf_to_poi']

 Numbers of features: 7

**Let's see what the best features are from the second set**

In [49]:
# Print importance of each feature
clf_ADA.fit(features_train,labels_train)
for feature, imp in zip(second_feature_list[1:],clf_ADA.feature_importances_):
    print feature +": " + str(round(imp,2))

exercised_stock_options: 0.07
restricted_stock: 0.0
shared_receipt_with_poi: 0.0
expenses: 0.14
other: 0.07
nf_to_poi: 0.21

In [50]:
# format the feature list
data = featureFormat(data_dict, all_features_list, sort_keys = True)
labels, features = targetFeatureSplit(data)


features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=42)

In [51]:
# Gridsearch for learning rate and estimator hyperparameters
parameters = {'learning_rate':[0.1, 0.2, 0.3, 0.5, 0.7,0.8, 0.9, 1, 2,3, 5, 10],'n_estimators':[1,5,8,10,11, 12, 13, 14, 15, 16, 17, 18,50,100,1000, 2000] }
clf_ADA = AdaBoostClassifier()
clf = GridSearchCV(clf_ADA, parameters, scoring = 'f1', cv = 10 )
clf.fit(features, labels)



print clf.best_params_
print clf.best_score_

{'n_estimators': 13, 'learning_rate': 0.9}
0.49941724941724935

In [52]:
lr = clf.best_params_['learning_rate']
n_est = clf.best_params_['n_estimators']
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, second_feature_list)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=0.9, n_estimators=13, random_state=None)
	Accuracy: 0.89267	Precision: 0.63430	Recall: 0.46050	F1: 0.53360	F2: 0.48720
	Total predictions: 15000	True positives:  921	False positives:  531	False negatives: 1079	True negatives: 12469

**performance tests**

**trying some other hyperparameters**

In [53]:
lr = 0.9
n_est = 14
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, second_feature_list)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=0.9, n_estimators=14, random_state=None)
	Accuracy: 0.89413	Precision: 0.63807	Recall: 0.47600	F1: 0.54525	F2: 0.50147
	Total predictions: 15000	True positives:  952	False positives:  540	False negatives: 1048	True negatives: 12460

best so far, but let's keep trying

# Classifier Tuning - Third Feature List

In [54]:
# creating a new list from the important features
feature_list_three = ['poi']
for feature, imp in zip(first_feature_list[1:],clf_ADA.feature_importances_):
    if imp > 0.00:
        feature_list_three.append(feature)

In [55]:
# Take the best importance from the second list
third_feature_list = feature_list_three



# print the feature list
print  third_feature_list
print "\n Numbers of features: " + str(len(third_feature_list))

['poi', 'total_payments', 'exercised_stock_options', 'restricted_stock', 'shared_receipt_with_poi', 'total_stock_value']

 Numbers of features: 6

In [56]:
# Print importance of each feature
clf_ADA.fit(features_train,labels_train)
for feature, imp in zip(third_feature_list[1:],clf_ADA.feature_importances_):
    print feature +": " + str(round(imp,2))

total_payments: 0.07
exercised_stock_options: 0.0
restricted_stock: 0.0
shared_receipt_with_poi: 0.14
total_stock_value: 0.07

In [57]:
# format the feature list
data = featureFormat(data_dict, all_features_list, sort_keys = True)
labels, features = targetFeatureSplit(data)


features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=42)

In [58]:
# Gridsearch for learning rate and estimator hyperparameters
parameters = {'learning_rate':[0.1, 0.2, 0.3, 0.5, 0.7,0.8, 0.9, 1, 2,3, 5, 10],'n_estimators':[1,5,8,10,11, 12, 13, 14, 15, 16, 17, 18,50,100,1000, 2000] }
clf_ADA = AdaBoostClassifier()
clf = GridSearchCV(clf_ADA, parameters, scoring = 'f1', cv = 10 )
clf.fit(features, labels)



print clf.best_params_
print clf.best_score_

{'n_estimators': 13, 'learning_rate': 0.9}
0.49941724941724935

In [59]:
lr = clf.best_params_['learning_rate']
n_est = clf.best_params_['n_estimators']
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, third_feature_list)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=0.9, n_estimators=13, random_state=None)
	Accuracy: 0.84600	Precision: 0.36953	Recall: 0.21950	F1: 0.27541	F2: 0.23890
	Total predictions: 15000	True positives:  439	False positives:  749	False negatives: 1561	True negatives: 12251

performance was worse stopping here

# Recursive Feature Selection and Tuning

Let's try recursive feature elimination to make the list.

In [61]:
from sklearn.feature_selection import RFE

In [62]:
# format the feature list
data = featureFormat(data_dict, first_feature_list, sort_keys = True)
labels, features = targetFeatureSplit(data)

In [63]:
# rank the features
rfe = RFE(clf_ADA,8)
selector = rfe.fit(features,labels)

In [64]:
# print he feature ranks
for feature, rank in zip(first_feature_list[1:], selector.ranking_ ):
    print feature +" (" + str(rank) +")"

total_payments (6)
exercised_stock_options (1)
bonus (5)
restricted_stock (4)
shared_receipt_with_poi (3)
total_stock_value (2)
expenses (1)
other (1)
nf_bonus (1)
nf_salary (1)
nf_exercised_stock (1)
nf_to_poi (1)
nf_poi_to (1)

In [65]:
# creating a new list from the ranked features
alt_feature_list_one = ['poi']
for feature, rank in zip(first_feature_list[1:], selector.ranking_ ):
    if rank < 6:
        alt_feature_list_one.append(feature)

In [66]:
# print the feature list
print  alt_feature_list_one
print "\n Numbers of features: " + str(len(alt_feature_list_one))

['poi', 'exercised_stock_options', 'bonus', 'restricted_stock', 'shared_receipt_with_poi', 'total_stock_value', 'expenses', 'other', 'nf_bonus', 'nf_salary', 'nf_exercised_stock', 'nf_to_poi', 'nf_poi_to']

 Numbers of features: 13

In [67]:
# format the feature list
data = featureFormat(data_dict,first_feature_list, sort_keys = True)
labels, features = targetFeatureSplit(data)


features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=42)

In [68]:
# Gridsearch for learning rate and estimator hyperparameters
parameters = {'learning_rate':[0.1, 0.2, 0.3, 0.5, 0.7,0.8, 0.9, 1, 2,3, 5, 10],'n_estimators':[1,5,8,10,11, 12, 13, 14, 15, 16, 17, 18,50,100,1000, 2000] }
clf_ADA = AdaBoostClassifier()
clf = GridSearchCV(clf_ADA, parameters, scoring = 'f1', cv = 10 )
clf.fit(features, labels)



print clf.best_params_
print clf.best_score_

{'n_estimators': 17, 'learning_rate': 0.8}
0.4848484848484848

In [69]:
lr = clf.best_params_['learning_rate']
n_est = clf.best_params_['n_estimators']
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, alt_feature_list_one)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=0.8, n_estimators=17, random_state=None)
	Accuracy: 0.85953	Precision: 0.46235	Recall: 0.32850	F1: 0.38410	F2: 0.34869
	Total predictions: 15000	True positives:  657	False positives:  764	False negatives: 1343	True negatives: 12236

better but let's keep going

**Let's see what the best features are from the second set**

In [70]:
# Print importance of each feature
clf_ADA.fit(features_train,labels_train)
for feature, imp in zip(alt_feature_list_one[1:],clf_ADA.feature_importances_):
    print feature +": " + str(round(imp,2))

exercised_stock_options: 0.18
bonus: 0.12
restricted_stock: 0.12
shared_receipt_with_poi: 0.0
total_stock_value: 0.06
expenses: 0.0
other: 0.18
nf_bonus: 0.12
nf_salary: 0.0
nf_exercised_stock: 0.06
nf_to_poi: 0.06
nf_poi_to: 0.12

In [71]:
# format the feature list
data = featureFormat(data_dict, first_feature_list, sort_keys = True)
labels, features = targetFeatureSplit(data)


rfe = RFE(clf_ADA,6)
selector = rfe.fit(features,labels)

In [72]:
# print the feature ranks
for feature, rank in zip(first_feature_list[1:], selector.ranking_ ):
    print feature +" (" + str(rank) +")"

total_payments (8)
exercised_stock_options (1)
bonus (7)
restricted_stock (1)
shared_receipt_with_poi (2)
total_stock_value (6)
expenses (1)
other (1)
nf_bonus (5)
nf_salary (4)
nf_exercised_stock (3)
nf_to_poi (1)
nf_poi_to (1)

**Alt Feature list 2**

In [73]:
# creating a new list from the ranked features
alt_feature_list_two = ['poi']
for feature, rank in zip(first_feature_list[1:], selector.ranking_ ):
    if rank < 4:
        alt_feature_list_two.append(feature)

In [74]:
# print the feature list
print  alt_feature_list_two
print "\n Numbers of features: " + str(len(alt_feature_list_two))

['poi', 'exercised_stock_options', 'restricted_stock', 'shared_receipt_with_poi', 'expenses', 'other', 'nf_exercised_stock', 'nf_to_poi', 'nf_poi_to']

 Numbers of features: 9

In [75]:
# reformat the feature list
data = featureFormat(data_dict, alt_feature_list_two, sort_keys = True)
labels, features = targetFeatureSplit(data)


features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=42)

In [76]:
# Gridsearch for learning rate and estimator hyperparameters
parameters = {'learning_rate':[0.1, 0.2, 0.3, 0.5, 0.7,0.8, 0.9, 1, 2,3, 5, 10],'n_estimators':[1,5,8,10,11, 12, 13, 14, 15, 16, 17, 18,50,100,1000, 2000] }
clf_ADA = AdaBoostClassifier()
clf = GridSearchCV(clf_ADA, parameters, scoring = 'f1', cv = 10 )
clf.fit(features, labels)

print clf.best_params_
print clf.best_score_

{'n_estimators': 15, 'learning_rate': 0.8}
0.5378250591016548

In [77]:
# test performance
lr = clf.best_params_['learning_rate']
n_est = clf.best_params_['n_estimators']
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, alt_feature_list_two)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=0.8, n_estimators=15, random_state=None)
	Accuracy: 0.88000	Precision: 0.56757	Recall: 0.42000	F1: 0.48276	F2: 0.44304
	Total predictions: 15000	True positives:  840	False positives:  640	False negatives: 1160	True negatives: 12360

In [78]:
# Print importance of each feature
clf_ADA.fit(features_train,labels_train)
for feature, imp in zip(alt_feature_list_two[1:],clf_ADA.feature_importances_):
    print feature +": " + str(round(imp,2))

exercised_stock_options: 0.07
restricted_stock: 0.13
shared_receipt_with_poi: 0.13
expenses: 0.07
other: 0.13
nf_exercised_stock: 0.27
nf_to_poi: 0.13
nf_poi_to: 0.07

In [79]:
# format the feature list
data = featureFormat(data_dict, first_feature_list, sort_keys = True)
labels, features = targetFeatureSplit(data)

rfe = RFE(clf_ADA,5)
selector = rfe.fit(features,labels)

In [80]:
# print the feature ranks
for feature, rank in zip(first_feature_list[1:], selector.ranking_ ):
    print feature +" (" + str(rank) +")"

total_payments (9)
exercised_stock_options (1)
bonus (8)
restricted_stock (1)
shared_receipt_with_poi (2)
total_stock_value (7)
expenses (1)
other (1)
nf_bonus (6)
nf_salary (5)
nf_exercised_stock (4)
nf_to_poi (1)
nf_poi_to (3)

**Alt Feature list 3**

In [81]:
# creating a new list from the ranked features
alt_feature_list_three = ['poi']
for feature, rank in zip(first_feature_list[1:], selector.ranking_ ):
    if rank < 2:
        alt_feature_list_three.append(feature)

In [82]:
# print the feature list
print  alt_feature_list_three
print "\n Numbers of features: " + str(len(alt_feature_list_three))

['poi', 'exercised_stock_options', 'restricted_stock', 'expenses', 'other', 'nf_to_poi']

 Numbers of features: 6

In [83]:
# reformat the feature list
data = featureFormat(data_dict, alt_feature_list_three, sort_keys = True)
labels, features = targetFeatureSplit(data)


features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=42)

In [84]:
# Gridsearch for learning rate and estimator hyperparameters
parameters = {'learning_rate':[0.1, 0.2, 0.3, 0.5, 0.7,0.8, 0.9, 1, 2,3, 5, 10],'n_estimators':[1,5,8,10,11, 12, 13, 14, 15, 16, 17, 18,50,100,1000, 2000] }
clf_ADA = AdaBoostClassifier()
clf = GridSearchCV(clf_ADA, parameters, scoring = 'f1', cv = 10 )
clf.fit(features, labels)

print clf.best_params_
print clf.best_score_

{'n_estimators': 16, 'learning_rate': 0.8}
0.6847619047619047

In [85]:
# test performance
lr = clf.best_params_['learning_rate']
n_est = clf.best_params_['n_estimators']
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, alt_feature_list_three)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=0.8, n_estimators=16, random_state=None)
	Accuracy: 0.89157	Precision: 0.66110	Recall: 0.49450	F1: 0.56579	F2: 0.52075
	Total predictions: 14000	True positives:  989	False positives:  507	False negatives: 1011	True negatives: 11493

**looking better let's see how far it can go**

In [86]:
# Print importance of each feature
clf_ADA.fit(features_train,labels_train)
for feature, imp in zip(alt_feature_list_three[1:],clf_ADA.feature_importances_):
    print feature +": " + str(round(imp,2))

exercised_stock_options: 0.19
restricted_stock: 0.13
expenses: 0.06
other: 0.38
nf_to_poi: 0.25

In [87]:
# print the feature ranks
for feature, rank in zip(first_feature_list[1:], selector.ranking_ ):
    print feature +" (" + str(rank) +")"

total_payments (9)
exercised_stock_options (1)
bonus (8)
restricted_stock (1)
shared_receipt_with_poi (2)
total_stock_value (7)
expenses (1)
other (1)
nf_bonus (6)
nf_salary (5)
nf_exercised_stock (4)
nf_to_poi (1)
nf_poi_to (3)

**Alt Feature list 4**

In [88]:
# creating a new list from the ranked features
alt_feature_list_four = ['poi']
for feature, rank in zip(first_feature_list[1:], selector.ranking_ ):
    if rank < 3:
        alt_feature_list_four.append(feature)

In [89]:
# print the feature list
print  alt_feature_list_four
print "\n Numbers of features: " + str(len(alt_feature_list_four))

['poi', 'exercised_stock_options', 'restricted_stock', 'shared_receipt_with_poi', 'expenses', 'other', 'nf_to_poi']

 Numbers of features: 7

In [90]:
# reformat the feature list
data = featureFormat(data_dict, alt_feature_list_four, sort_keys = True)
labels, features = targetFeatureSplit(data)


features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=42)

In [91]:
# Gridsearch for learning rate and estimator hyperparameters
parameters = {'learning_rate':[0.1, 0.2, 0.3, 0.5, 0.7,0.8, 0.9, 1, 2,3, 5, 10],
              'n_estimators':[1,5,8,10,11, 12, 13, 14, 15, 16, 17, 18,50,100,1000, 2000] }
clf_ADA = AdaBoostClassifier()
clf = GridSearchCV(clf_ADA, parameters, scoring = 'f1', cv = 10 )
clf.fit(features, labels)

print clf.best_params_
print clf.best_score_

{'n_estimators': 17, 'learning_rate': 1}
0.6323877068557919

In [92]:
# test performance
lr = clf.best_params_['learning_rate']
n_est = clf.best_params_['n_estimators']
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, alt_feature_list_four)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1,
          n_estimators=17, random_state=None)
	Accuracy: 0.89460	Precision: 0.63335	Recall: 0.49750	F1: 0.55727	F2: 0.51980
	Total predictions: 15000	True positives:  995	False positives:  576	False negatives: 1005	True negatives: 12424

**some fine tuning**

In [93]:
# test performance
lr = 1.0
n_est = 18
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, alt_feature_list_four)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=18, random_state=None)
	Accuracy: 0.89640	Precision: 0.64277	Recall: 0.50200	F1: 0.56373	F2: 0.52499
	Total predictions: 15000	True positives: 1004	False positives:  558	False negatives:  996	True negatives: 12442

In [94]:
# test performance
lr = 1.0
n_est = 19
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, alt_feature_list_four)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=19, random_state=None)
	Accuracy: 0.89573	Precision: 0.63956	Recall: 0.49950	F1: 0.56092	F2: 0.52238
	Total predictions: 15000	True positives:  999	False positives:  563	False negatives: 1001	True negatives: 12437

In [95]:
# test performance
lr = 1.0
n_est = 20
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, alt_feature_list_four)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=20, random_state=None)
	Accuracy: 0.89560	Precision: 0.63839	Recall: 0.50050	F1: 0.56110	F2: 0.52310
	Total predictions: 15000	True positives: 1001	False positives:  567	False negatives:  999	True negatives: 12433

In [96]:
# test performance
lr = 1.0
n_est = 16
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, alt_feature_list_four)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=16, random_state=None)
	Accuracy: 0.89407	Precision: 0.63148	Recall: 0.49350	F1: 0.55403	F2: 0.51605
	Total predictions: 15000	True positives:  987	False positives:  576	False negatives: 1013	True negatives: 12424

In [97]:
# test performance
lr = 1.0
n_est = 15
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, alt_feature_list_four)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=15, random_state=None)
	Accuracy: 0.89440	Precision: 0.63506	Recall: 0.48900	F1: 0.55254	F2: 0.51258
	Total predictions: 15000	True positives:  978	False positives:  562	False negatives: 1022	True negatives: 12438

In [99]:
# test performance
lr = 0.9
n_est = 18
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, alt_feature_list_four)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=0.9, n_estimators=18, random_state=None)
	Accuracy: 0.89540	Precision: 0.64150	Recall: 0.48850	F1: 0.55464	F2: 0.51297
	Total predictions: 15000	True positives:  977	False positives:  546	False negatives: 1023	True negatives: 12454

**think this might be as good as it gets**

# Best Feature List

In [100]:
final_feature_list = alt_feature_list_four

# print the feature list
print  final_feature_list
print "\n Numbers of features: " + str(len(final_feature_list))

['poi', 'exercised_stock_options', 'restricted_stock', 'shared_receipt_with_poi', 'expenses', 'other', 'nf_to_poi']

 Numbers of features: 7

In [101]:
# format the feature list
data = featureFormat(data_dict, final_feature_list, sort_keys = True)
labels, features = targetFeatureSplit(data)

features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=42)


# Gridsearch for learning rate and estimator hyperparameters
parameters = {'learning_rate':[0.1, 0.2, 0.3, 0.5, 0.7,0.8, 0.9, 1, 2,3, 5, 10],
              'n_estimators':[1,5,8,10,11, 12, 13, 14, 15, 16, 17, 18,50,100,1000, 2000] }
clf_ADA = AdaBoostClassifier()

clf = GridSearchCV(clf_ADA, parameters, scoring = 'f1', cv = 10 )
clf.fit(features, labels)

print clf.best_params_
print clf.best_score_

{'n_estimators': 17, 'learning_rate': 1}
0.6323877068557919

In [102]:
# test performance
lr = 1.0
n_est = 18
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, final_feature_list)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=18, random_state=None)
	Accuracy: 0.89647	Precision: 0.64318	Recall: 0.50200	F1: 0.56389	F2: 0.52505
	Total predictions: 15000	True positives: 1004	False positives:  557	False negatives:  996	True negatives: 12443

**final tuning**

In [103]:
# test performance
lr = 1.0
n_est = 18
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, final_feature_list)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=18, random_state=None)
	Accuracy: 0.89647	Precision: 0.64318	Recall: 0.50200	F1: 0.56389	F2: 0.52505
	Total predictions: 15000	True positives: 1004	False positives:  557	False negatives:  996	True negatives: 12443

In [104]:
# test performance
lr = 1.05
n_est = 18
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, final_feature_list)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.05, n_estimators=18, random_state=None)
	Accuracy: 0.89380	Precision: 0.63020	Recall: 0.49250	F1: 0.55290	F2: 0.51501
	Total predictions: 15000	True positives:  985	False positives:  578	False negatives: 1015	True negatives: 12422

In [105]:
# test performance
lr = 1.0
n_est = 19
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, final_feature_list)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=19, random_state=None)
	Accuracy: 0.89573	Precision: 0.63956	Recall: 0.49950	F1: 0.56092	F2: 0.52238
	Total predictions: 15000	True positives:  999	False positives:  563	False negatives: 1001	True negatives: 12437

In [106]:
# test performance
lr = 0.95
n_est = 18
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, final_feature_list)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=0.95, n_estimators=18, random_state=None)
	Accuracy: 0.89480	Precision: 0.63863	Recall: 0.48600	F1: 0.55196	F2: 0.51040
	Total predictions: 15000	True positives:  972	False positives:  550	False negatives: 1028	True negatives: 12450

In [107]:
# test performance
lr = 0.9
n_est = 18
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, final_feature_list)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=0.9, n_estimators=18, random_state=None)
	Accuracy: 0.89533	Precision: 0.64126	Recall: 0.48800	F1: 0.55423	F2: 0.51250
	Total predictions: 15000	True positives:  976	False positives:  546	False negatives: 1024	True negatives: 12454

# Created Features Performance

In [108]:
# format the feature list
data = featureFormat(data_dict, final_feature_list, sort_keys = True)
labels, features = targetFeatureSplit(data)

features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=42)

# Final feature selection 
final_feature_list = ['poi', 'exercised_stock_options', 'restricted_stock', 'shared_receipt_with_poi', 'expenses', 'other', 
                      'nf_to_poi'] 


# print the features
print  final_feature_list
print "\n Numbers of features: " + str(len(final_feature_list))

# Test
lr = 1.0
n_est = 18
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, final_feature_list)

['poi', 'exercised_stock_options', 'restricted_stock', 'shared_receipt_with_poi', 'expenses', 'other', 'nf_to_poi']

 Numbers of features: 7
AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=18, random_state=None)
	Accuracy: 0.89647	Precision: 0.64318	Recall: 0.50200	F1: 0.56389	F2: 0.52505
	Total predictions: 15000	True positives: 1004	False positives:  557	False negatives:  996	True negatives: 12443

**ony one created feature lasted this far**

In [109]:
# format the feature list
data = featureFormat(data_dict, final_feature_list, sort_keys = True)
labels, features = targetFeatureSplit(data)

features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=42)

# features list with the created feature removed
final_feature_list = ['poi', 'exercised_stock_options', 'restricted_stock', 
                      'shared_receipt_with_poi', 'expenses', 'other' 
                      ] 

# print the feature list
print  final_feature_list
print "\n Numbers of features: " + str(len(final_feature_list))

# Test
lr = 1.0
n_est = 18
clf_ADA = AdaBoostClassifier(learning_rate = lr, n_estimators = n_est)
test_classifier(clf_ADA, data_dict, final_feature_list)

['poi', 'exercised_stock_options', 'restricted_stock', 'shared_receipt_with_poi', 'expenses', 'other']

 Numbers of features: 6
AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=18, random_state=None)
	Accuracy: 0.86820	Precision: 0.50805	Recall: 0.36300	F1: 0.42345	F2: 0.38498
	Total predictions: 15000	True positives:  726	False positives:  703	False negatives: 1274	True negatives: 12297

**Looks like without the created feature accuracy, precision, and recall suffer performance loss**